<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HanziTraditionalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // hanzi Traditional Hanzi (236)
        DB::table('hanzi')->insert([
            ['hanzi' => '戶', 'pinyin' => 'hù', 'pinyin_eng' => 'hu', 'meaning_thai' => 'ครอบครัว', 'meaning_english' => 'household'],
            ['hanzi' => '見', 'pinyin' => 'jiàn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'เห็น', 'meaning_english' => 'see'],
            ['hanzi' => '貝', 'pinyin' => 'bèi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'หอย', 'meaning_english' => 'shellfish'],
            ['hanzi' => '艸', 'pinyin' => 'cǎo', 'pinyin_eng' => 'cao', 'meaning_thai' => 'หญ้า', 'meaning_english' => 'grass'],
            ['hanzi' => '車', 'pinyin' => 'chē', 'pinyin_eng' => 'che', 'meaning_thai' => 'ยานพาหนะ', 'meaning_english' => 'vehicle'],
            ['hanzi' => '長', 'pinyin' => 'cháng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'ยาว', 'meaning_english' => 'long'],
            ['hanzi' => '門', 'pinyin' => 'mén', 'pinyin_eng' => 'men', 'meaning_thai' => 'ประตู', 'meaning_english' => 'door'],
            ['hanzi' => '靑', 'pinyin' => 'qīng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'สีเขียว', 'meaning_english' => 'green'],
            ['hanzi' => '韋', 'pinyin' => 'wéi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'หนังฟอก', 'meaning_english' => 'tanned leather'],
            ['hanzi' => '頁', 'pinyin' => 'yè', 'pinyin_eng' => 'ye', 'meaning_thai' => 'หน้า', 'meaning_english' => 'page'],
            ['hanzi' => '風', 'pinyin' => 'fēng', 'pinyin_eng' => 'feng', 'meaning_thai' => 'ลม', 'meaning_english' => 'wind'],
            ['hanzi' => '飛', 'pinyin' => 'fēi', 'pinyin_eng' => 'fei', 'meaning_thai' => 'บิน', 'meaning_english' => 'fly'],
            ['hanzi' => '馬', 'pinyin' => 'mǎ', 'pinyin_eng' => 'ma', 'meaning_thai' => 'ม้า', 'meaning_english' => 'horse'],
            ['hanzi' => '鬥', 'pinyin' => 'dòu', 'pinyin_eng' => 'dou', 'meaning_thai' => 'ต่อสู้', 'meaning_english' => 'fight'],
            ['hanzi' => '魚', 'pinyin' => 'yú', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ปลา', 'meaning_english' => 'fish'],
            ['hanzi' => '鳥', 'pinyin' => 'niǎo', 'pinyin_eng' => 'niao', 'meaning_thai' => 'นก', 'meaning_english' => 'bird'],
            ['hanzi' => '鹵', 'pinyin' => 'lǔ', 'pinyin_eng' => 'lu', 'meaning_thai' => 'เกลือ', 'meaning_english' => 'salt'],
            ['hanzi' => '麥', 'pinyin' => 'mài', 'pinyin_eng' => 'mai', 'meaning_thai' => 'ข้าวสาลี', 'meaning_english' => 'wheat'],
            ['hanzi' => '黃', 'pinyin' => 'huáng', 'pinyin_eng' => 'huang', 'meaning_thai' => 'สีเหลือง', 'meaning_english' => 'yellow'],
            ['hanzi' => '黽', 'pinyin' => 'mǐn', 'pinyin_eng' => 'min', 'meaning_thai' => 'กบ', 'meaning_english' => 'frog'],
            ['hanzi' => '齊', 'pinyin' => 'qí', 'pinyin_eng' => 'qi', 'meaning_thai' => 'พร้อมกัน', 'meaning_english' => 'together'],
            ['hanzi' => '齒', 'pinyin' => 'chǐ', 'pinyin_eng' => 'chi', 'meaning_thai' => 'ฟัน', 'meaning_english' => 'tooth'],
            ['hanzi' => '龍', 'pinyin' => 'lóng', 'pinyin_eng' => 'long', 'meaning_thai' => 'มังกร', 'meaning_english' => 'dragon'],
            ['hanzi' => '龜', 'pinyin' => 'guī', 'pinyin_eng' => 'gui', 'meaning_thai' => 'เต่า', 'meaning_english' => 'turtle'],
            ['hanzi' => '愛', 'pinyin' => 'ài', 'pinyin_eng' => 'ai', 'meaning_thai' => 'รัก', 'meaning_english' => 'love'],
            ['hanzi' => '氣', 'pinyin' => 'qì', 'pinyin_eng' => 'qi', 'meaning_thai' => 'อากาศ', 'meaning_english' => 'air'],
            ['hanzi' => '電', 'pinyin' => 'diàn', 'pinyin_eng' => 'dian', 'meaning_thai' => 'ไฟฟ้า', 'meaning_english' => 'electricity'],
            ['hanzi' => '話', 'pinyin' => 'huà', 'pinyin_eng' => 'hua', 'meaning_thai' => 'คำพูด', 'meaning_english' => 'speech'],
            ['hanzi' => '點', 'pinyin' => 'diǎn', 'pinyin_eng' => 'dian', 'meaning_thai' => 'จุด', 'meaning_english' => 'point'],
            ['hanzi' => '腦', 'pinyin' => 'nǎo', 'pinyin_eng' => 'nao', 'meaning_thai' => 'สมอง', 'meaning_english' => 'brain'],
            ['hanzi' => '視', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'มอง', 'meaning_english' => 'look'],
            ['hanzi' => '東', 'pinyin' => 'dōng', 'pinyin_eng' => 'dong', 'meaning_thai' => 'ทิศตะวันออก', 'meaning_english' => 'east'],
            ['hanzi' => '讀', 'pinyin' => 'dú', 'pinyin_eng' => 'du', 'meaning_thai' => 'อ่าน', 'meaning_english' => 'read'],
            ['hanzi' => '對', 'pinyin' => 'duì', 'pinyin_eng' => 'dui', 'meaning_thai' => 'ถูกต้อง', 'meaning_english' => 'correct'],
            ['hanzi' => '兒', 'pinyin' => 'ér', 'pinyin_eng' => 'er', 'meaning_thai' => 'เด็ก', 'meaning_english' => 'child'],
            ['hanzi' => '飯', 'pinyin' => 'fàn', 'pinyin_eng' => 'fan', 'meaning_thai' => 'ข้าว', 'meaning_english' => 'rice'],
            ['hanzi' => '館', 'pinyin' => 'guǎn', 'pinyin_eng' => 'guan', 'meaning_thai' => 'ห้องโถง', 'meaning_english' => 'hall'],
            ['hanzi' => '機', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'เครื่องจักร', 'meaning_english' => 'machine'],
            ['hanzi' => '鐘', 'pinyin' => 'zhōng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'นาฬิกา', 'meaning_english' => 'clock'],
            ['hanzi' => '興', 'pinyin' => 'xìng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'ความสนใจ', 'meaning_english' => 'interest'],
            ['hanzi' => '個', 'pinyin' => 'gè', 'pinyin_eng' => 'ge', 'meaning_thai' => 'บุคคล', 'meaning_english' => 'individual'],
            ['hanzi' => '漢', 'pinyin' => 'hàn', 'pinyin_eng' => 'han', 'meaning_thai' => 'ฮั่น', 'meaning_english' => 'Han'],
            ['hanzi' => '語', 'pinyin' => 'yǔ', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ภาษา', 'meaning_english' => 'language'],
            ['hanzi' => '後', 'pinyin' => 'hòu', 'pinyin_eng' => 'hou', 'meaning_thai' => 'หลังจาก', 'meaning_english' => 'after'],
            ['hanzi' => '會', 'pinyin' => 'huì', 'pinyin_eng' => 'hui', 'meaning_thai' => 'การประชุม', 'meaning_english' => 'meeting'],
            ['hanzi' => '幾', 'pinyin' => 'jǐ', 'pinyin_eng' => 'ji', 'meaning_thai' => 'กี่', 'meaning_english' => 'how many'],
            ['hanzi' => '開', 'pinyin' => 'kāi', 'pinyin_eng' => 'kai', 'meaning_thai' => 'เปิด', 'meaning_english' => 'open'],
            ['hanzi' => '塊', 'pinyin' => 'kuài', 'pinyin_eng' => 'kuai', 'meaning_thai' => 'ชิ้น', 'meaning_english' => 'piece'],
            ['hanzi' => '來', 'pinyin' => 'lái', 'pinyin_eng' => 'lai', 'meaning_thai' => 'มา', 'meaning_english' => 'come'],
            ['hanzi' => '師', 'pinyin' => 'shī', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ครู', 'meaning_english' => 'teacher'],
            ['hanzi' => '裡', 'pinyin' => 'lǐ', 'pinyin_eng' => 'li', 'meaning_thai' => 'ข้างใน', 'meaning_english' => 'inside'],
            ['hanzi' => '媽', 'pinyin' => 'mā', 'pinyin_eng' => 'ma', 'meaning_thai' => 'แม่', 'meaning_english' => 'mother'],
            ['hanzi' => '嗎', 'pinyin' => 'ma', 'pinyin_eng' => 'ma', 'meaning_thai' => 'คำถาม', 'meaning_english' => 'question particle'],
            ['hanzi' => '買', 'pinyin' => 'mǎi', 'pinyin_eng' => 'mai', 'meaning_thai' => 'ซื้อ', 'meaning_english' => 'buy'],
            ['hanzi' => '貓', 'pinyin' => 'māo', 'pinyin_eng' => 'mao', 'meaning_thai' => 'แมว', 'meaning_english' => 'cat'],
            ['hanzi' => '沒', 'pinyin' => 'méi', 'pinyin_eng' => 'mei', 'meaning_thai' => 'ไม่', 'meaning_english' => 'not'],
            ['hanzi' => '關', 'pinyin' => 'guān', 'pinyin_eng' => 'guan', 'meaning_thai' => 'ปิด', 'meaning_english' => 'close'],
            ['hanzi' => '係', 'pinyin' => 'xì', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ระบบ', 'meaning_english' => 'system'],
            ['hanzi' => '蘋', 'pinyin' => 'píng', 'pinyin_eng' => 'ping', 'meaning_thai' => 'แอปเปิ้ล', 'meaning_english' => 'apple'],
            ['hanzi' => '錢', 'pinyin' => 'qián', 'pinyin_eng' => 'qian', 'meaning_thai' => 'เงิน', 'meaning_english' => 'money'],
            ['hanzi' => '請', 'pinyin' => 'qǐng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'กรุณา', 'meaning_english' => 'please'],
            ['hanzi' => '熱', 'pinyin' => 'rè', 'pinyin_eng' => 're', 'meaning_thai' => 'ร้อน', 'meaning_english' => 'hot'],
            ['hanzi' => '認', 'pinyin' => 'rèn', 'pinyin_eng' => 'ren', 'meaning_thai' => 'จำได้', 'meaning_english' => 'recognize'],
            ['hanzi' => '識', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'รู้', 'meaning_english' => 'know'],
            ['hanzi' => '誰', 'pinyin' => 'shéi', 'pinyin_eng' => 'shei', 'meaning_thai' => 'ใคร', 'meaning_english' => 'who'],
            ['hanzi' => '麼', 'pinyin' => 'me', 'pinyin_eng' => 'me', 'meaning_thai' => 'คำถาม', 'meaning_english' => 'question particle'],
            ['hanzi' => '時', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'เวลา', 'meaning_english' => 'time'],
            ['hanzi' => '書', 'pinyin' => 'shū', 'pinyin_eng' => 'shu', 'meaning_thai' => 'หนังสือ', 'meaning_english' => 'book'],
            ['hanzi' => '覺', 'pinyin' => 'jué', 'pinyin_eng' => 'jue', 'meaning_thai' => 'รู้สึก', 'meaning_english' => 'feel'],
            ['hanzi' => '說', 'pinyin' => 'shuō', 'pinyin_eng' => 'shuo', 'meaning_thai' => 'พูด', 'meaning_english' => 'speak'],
            ['hanzi' => '歲', 'pinyin' => 'suì', 'pinyin_eng' => 'sui', 'meaning_thai' => 'ปี', 'meaning_english' => 'year'],
            ['hanzi' => '聽', 'pinyin' => 'tīng', 'pinyin_eng' => 'ting', 'meaning_thai' => 'ฟัง', 'meaning_english' => 'listen'],
            ['hanzi' => '學', 'pinyin' => 'xué', 'pinyin_eng' => 'xue', 'meaning_thai' => 'เรียน', 'meaning_english' => 'learn'],
            ['hanzi' => '餵', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'ให้อาหาร', 'meaning_english' => 'feed'],
            ['hanzi' => '們', 'pinyin' => 'men', 'pinyin_eng' => 'men', 'meaning_thai' => 'คำบอกพหูพจน์', 'meaning_english' => 'plural marker'],
            ['hanzi' => '歡', 'pinyin' => 'huān', 'pinyin_eng' => 'huan', 'meaning_thai' => 'มีความสุข', 'meaning_english' => 'happy'],
            ['hanzi' => '現', 'pinyin' => 'xiàn', 'pinyin_eng' => 'xian', 'meaning_thai' => 'ปัจจุบัน', 'meaning_english' => 'present'],
            ['hanzi' => '寫', 'pinyin' => 'xiě', 'pinyin_eng' => 'xie', 'meaning_thai' => 'เขียน', 'meaning_english' => 'write'],
            ['hanzi' => '謝', 'pinyin' => 'xiè', 'pinyin_eng' => 'xie', 'meaning_thai' => 'ขอบคุณ', 'meaning_english' => 'thank'],
            ['hanzi' => '習', 'pinyin' => 'xí', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ฝึกฝน', 'meaning_english' => 'practice'],
            ['hanzi' => '醫', 'pinyin' => 'yī', 'pinyin_eng' => 'yi', 'meaning_thai' => 'หมอ', 'meaning_english' => 'doctor'],
            ['hanzi' => '樣', 'pinyin' => 'yàng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'ชนิด', 'meaning_english' => 'kind'],
            ['hanzi' => '這', 'pinyin' => 'zhè', 'pinyin_eng' => 'zhe', 'meaning_thai' => 'นี้', 'meaning_english' => 'this'],
            ['hanzi' => '國', 'pinyin' => 'guó', 'pinyin_eng' => 'guo', 'meaning_thai' => 'ประเทศ', 'meaning_english' => 'country'],
            ['hanzi' => '繫', 'pinyin' => 'xì', 'pinyin_eng' => 'xi', 'meaning_thai' => 'เชื่อมต่อ', 'meaning_english' => 'connect'],
            ['hanzi' => '説', 'pinyin' => 'shuō', 'pinyin_eng' => 'shuo', 'meaning_thai' => 'พูด', 'meaning_english' => 'speak'],
            ['hanzi' => '為', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'สำหรับ', 'meaning_english' => 'for'],
            ['hanzi' => '過', 'pinyin' => 'guò', 'pinyin_eng' => 'guo', 'meaning_thai' => 'ผ่าน', 'meaning_english' => 'pass'],
            ['hanzi' => '還', 'pinyin' => 'hái', 'pinyin_eng' => 'hai', 'meaning_thai' => 'ยัง', 'meaning_english' => 'still'],
            ['hanzi' => '眞', 'pinyin' => 'zhēn', 'pinyin_eng' => 'zhen', 'meaning_thai' => 'จริง', 'meaning_english' => 'TRUE'],
            ['hanzi' => '讓', 'pinyin' => 'ràng', 'pinyin_eng' => 'rang', 'meaning_thai' => 'ให้', 'meaning_english' => 'let'],
            ['hanzi' => '給', 'pinyin' => 'gěi', 'pinyin_eng' => 'gei', 'meaning_thai' => 'ให้', 'meaning_english' => 'give'],
            ['hanzi' => '別', 'pinyin' => 'bié', 'pinyin_eng' => 'bie', 'meaning_thai' => 'อื่นๆ', 'meaning_english' => 'other'],
            ['hanzi' => '彆', 'pinyin' => 'bié', 'pinyin_eng' => 'bie', 'meaning_thai' => 'อื่นๆ', 'meaning_english' => 'other'],
            ['hanzi' => '經', 'pinyin' => 'jīng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'ผ่าน', 'meaning_english' => 'pass'],
            ['hanzi' => '從', 'pinyin' => 'cóng', 'pinyin_eng' => 'cong', 'meaning_thai' => 'จาก', 'meaning_english' => 'from'],
            ['hanzi' => '訴', 'pinyin' => 'sù', 'pinyin_eng' => 'su', 'meaning_thai' => 'บอก', 'meaning_english' => 'tell'],
            ['hanzi' => '問', 'pinyin' => 'wèn', 'pinyin_eng' => 'wen', 'meaning_thai' => 'ถาม', 'meaning_english' => 'ask'],
            ['hanzi' => '錯', 'pinyin' => 'cuò', 'pinyin_eng' => 'cuo', 'meaning_thai' => 'ผิด', 'meaning_english' => 'wrong'],
            ['hanzi' => '間', 'pinyin' => 'jiān', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ระหว่าง', 'meaning_english' => 'between'],
            ['hanzi' => '進', 'pinyin' => 'jìn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'เข้า', 'meaning_english' => 'enter'],
            ['hanzi' => '幫', 'pinyin' => 'bāng', 'pinyin_eng' => 'bang', 'meaning_thai' => 'ช่วย', 'meaning_english' => 'help'],
            ['hanzi' => '動', 'pinyin' => 'dòng', 'pinyin_eng' => 'dong', 'meaning_thai' => 'เคลื่อนที่', 'meaning_english' => 'move'],
            ['hanzi' => '兩', 'pinyin' => 'liǎng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'สอง', 'meaning_english' => 'two'],
            ['hanzi' => '題', 'pinyin' => 'tí', 'pinyin_eng' => 'ti', 'meaning_thai' => 'หัวข้อ', 'meaning_english' => 'topic'],
            ['hanzi' => '離', 'pinyin' => 'lí', 'pinyin_eng' => 'li', 'meaning_thai' => 'ออกจาก', 'meaning_english' => 'leave'],
            ['hanzi' => '場', 'pinyin' => 'chǎng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'ทุ่งนา', 'meaning_english' => 'field'],
            ['hanzi' => '錶', 'pinyin' => 'biǎo', 'pinyin_eng' => 'biao', 'meaning_thai' => 'นาฬิกา', 'meaning_english' => 'watch'],
            ['hanzi' => '邊', 'pinyin' => 'biān', 'pinyin_eng' => 'bian', 'meaning_thai' => 'ด้านข้าง', 'meaning_english' => 'side'],
            ['hanzi' => '準', 'pinyin' => 'zhǔn', 'pinyin_eng' => 'zhun', 'meaning_thai' => 'ถูกต้อง', 'meaning_english' => 'accurate'],
            ['hanzi' => '員', 'pinyin' => 'yuán', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'สมาชิก', 'meaning_english' => 'member'],
            ['hanzi' => '備', 'pinyin' => 'bèi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'เตรียม', 'meaning_english' => 'prepare'],
            ['hanzi' => '試', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ลอง', 'meaning_english' => 'try'],
            ['hanzi' => '體', 'pinyin' => 'tǐ', 'pinyin_eng' => 'ti', 'meaning_thai' => 'ร่างกาย', 'meaning_english' => 'body'],
            ['hanzi' => '樂', 'pinyin' => 'lè', 'pinyin_eng' => 'le', 'meaning_thai' => 'มีความสุข', 'meaning_english' => 'happy'],
            ['hanzi' => '報', 'pinyin' => 'bào', 'pinyin_eng' => 'bao', 'meaning_thai' => 'รายงาน', 'meaning_english' => 'report'],
            ['hanzi' => '遠', 'pinyin' => 'yuǎn', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'ไกล', 'meaning_english' => 'far'],
            ['hanzi' => '運', 'pinyin' => 'yùn', 'pinyin_eng' => 'yun', 'meaning_thai' => 'ขนส่ง', 'meaning_english' => 'transport'],
            ['hanzi' => '條', 'pinyin' => 'tiáo', 'pinyin_eng' => 'tiao', 'meaning_thai' => 'แถบ', 'meaning_english' => 'strip'],
            ['hanzi' => '務', 'pinyin' => 'wù', 'pinyin_eng' => 'wu', 'meaning_thai' => 'เรื่อง', 'meaning_english' => 'affair'],
            ['hanzi' => '遊', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'เล่น', 'meaning_english' => 'play'],
            ['hanzi' => '藥', 'pinyin' => 'yào', 'pinyin_eng' => 'yao', 'meaning_thai' => 'ยา', 'meaning_english' => 'medicine'],
            ['hanzi' => '賣', 'pinyin' => 'mài', 'pinyin_eng' => 'mai', 'meaning_thai' => 'ขาย', 'meaning_english' => 'sell'],
            ['hanzi' => '韆', 'pinyin' => 'qiān', 'pinyin_eng' => 'qian', 'meaning_thai' => 'พัน', 'meaning_english' => 'thousand'],
            ['hanzi' => '紅', 'pinyin' => 'hóng', 'pinyin_eng' => 'hong', 'meaning_thai' => 'สีแดง', 'meaning_english' => 'red'],
            ['hanzi' => '雞', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ไก่', 'meaning_english' => 'chicken'],
            ['hanzi' => '筆', 'pinyin' => 'bǐ', 'pinyin_eng' => 'bi', 'meaning_thai' => 'ปากกา', 'meaning_english' => 'pen'],
            ['hanzi' => '雖', 'pinyin' => 'suī', 'pinyin_eng' => 'sui', 'meaning_thai' => 'แม้ว่า', 'meaning_english' => 'although'],
            ['hanzi' => '課', 'pinyin' => 'kè', 'pinyin_eng' => 'ke', 'meaning_thai' => 'บทเรียน', 'meaning_english' => 'lesson'],
            ['hanzi' => '紙', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'กระดาษ', 'meaning_english' => 'paper'],
            ['hanzi' => '貴', 'pinyin' => 'guì', 'pinyin_eng' => 'gui', 'meaning_thai' => 'แพง', 'meaning_english' => 'expensive'],
            ['hanzi' => '陰', 'pinyin' => 'yīn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'ร่มเงา', 'meaning_english' => 'shade'],
            ['hanzi' => '紹', 'pinyin' => 'shào', 'pinyin_eng' => 'shao', 'meaning_thai' => 'ดำเนินต่อ', 'meaning_english' => 'continue'],
            ['hanzi' => '賓', 'pinyin' => 'bīn', 'pinyin_eng' => 'bin', 'meaning_thai' => 'แขก', 'meaning_english' => 'guest'],
            ['hanzi' => '顏', 'pinyin' => 'yán', 'pinyin_eng' => 'yan', 'meaning_thai' => 'ใบหน้า', 'meaning_english' => 'face'],
            ['hanzi' => '籃', 'pinyin' => 'lán', 'pinyin_eng' => 'lan', 'meaning_thai' => 'ตะกร้า', 'meaning_english' => 'basket'],
            ['hanzi' => '鉛', 'pinyin' => 'qiān', 'pinyin_eng' => 'qian', 'meaning_thai' => 'ตะกั่ว', 'meaning_english' => 'lead'],
            ['hanzi' => '發', 'pinyin' => 'fā', 'pinyin_eng' => 'fa', 'meaning_thai' => 'ส่งออก', 'meaning_english' => 'send out'],
            ['hanzi' => '髮', 'pinyin' => 'fà', 'pinyin_eng' => 'fa', 'meaning_thai' => 'ผม', 'meaning_english' => 'hair'],
            ['hanzi' => '該', 'pinyin' => 'gāi', 'pinyin_eng' => 'gai', 'meaning_thai' => 'ควร', 'meaning_english' => 'should'],
            ['hanzi' => '當', 'pinyin' => 'dāng', 'pinyin_eng' => 'dang', 'meaning_thai' => 'ควร', 'meaning_english' => 'should'],
            ['hanzi' => '噹', 'pinyin' => 'dāng', 'pinyin_eng' => 'dang', 'meaning_thai' => 'เสียงระฆัง', 'meaning_english' => 'sound of a bell'],
            ['hanzi' => '幹', 'pinyin' => 'gàn', 'pinyin_eng' => 'gan', 'meaning_thai' => 'ทำ', 'meaning_english' => 'do'],
            ['hanzi' => '實', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'จริง', 'meaning_english' => 'real'],
            ['hanzi' => '應', 'pinyin' => 'yīng', 'pinyin_eng' => 'ying', 'meaning_thai' => 'ควร', 'meaning_english' => 'should'],
            ['hanzi' => '頭', 'pinyin' => 'tóu', 'pinyin_eng' => 'tou', 'meaning_thai' => 'หัว', 'meaning_english' => 'head'],
            ['hanzi' => '帶', 'pinyin' => 'dài', 'pinyin_eng' => 'dai', 'meaning_thai' => 'นำมา', 'meaning_english' => 'bring'],
            ['hanzi' => '種', 'pinyin' => 'zhǒng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'ชนิด', 'meaning_english' => 'kind'],
            ['hanzi' => '記', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'จำได้', 'meaning_english' => 'remember'],
            ['hanzi' => '結', 'pinyin' => 'jié', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ผูก', 'meaning_english' => 'tie'],
            ['hanzi' => '難', 'pinyin' => 'nán', 'pinyin_eng' => 'nan', 'meaning_thai' => 'ยาก', 'meaning_english' => 'difficult'],
            ['hanzi' => '剛', 'pinyin' => 'gāng', 'pinyin_eng' => 'gang', 'meaning_thai' => 'เพิ่งจะ', 'meaning_english' => 'just'],
            ['hanzi' => '變', 'pinyin' => 'biàn', 'pinyin_eng' => 'bian', 'meaning_thai' => 'เปลี่ยน', 'meaning_english' => 'change'],
            ['hanzi' => '總', 'pinyin' => 'zǒng', 'pinyin_eng' => 'zong', 'meaning_thai' => 'ทั่วไป', 'meaning_english' => 'general'],
            ['hanzi' => '辦', 'pinyin' => 'bàn', 'pinyin_eng' => 'ban', 'meaning_thai' => 'ทำ', 'meaning_english' => 'do'],
            ['hanzi' => '選', 'pinyin' => 'xuǎn', 'pinyin_eng' => 'xuan', 'meaning_thai' => 'เลือก', 'meaning_english' => 'choose'],
            ['hanzi' => '決', 'pinyin' => 'jué', 'pinyin_eng' => 'jue', 'meaning_thai' => 'ตัดสินใจ', 'meaning_english' => 'decide'],
            ['hanzi' => '賽', 'pinyin' => 'sài', 'pinyin_eng' => 'sai', 'meaning_thai' => 'การแข่งขัน', 'meaning_english' => 'competition'],
            ['hanzi' => '須', 'pinyin' => 'xū', 'pinyin_eng' => 'xu', 'meaning_thai' => 'ต้อง', 'meaning_english' => 'must'],
            ['hanzi' => '單', 'pinyin' => 'dān', 'pinyin_eng' => 'dan', 'meaning_thai' => 'เดี่ยว', 'meaning_english' => 'single'],
            ['hanzi' => '張', 'pinyin' => 'zhāng', 'pinyin_eng' => 'zhang', 'meaning_thai' => 'แผ่น', 'meaning_english' => 'sheet'],
            ['hanzi' => '萬', 'pinyin' => 'wàn', 'pinyin_eng' => 'wan', 'meaning_thai' => 'หมื่น', 'meaning_english' => 'ten thousand'],
            ['hanzi' => '聲', 'pinyin' => 'shēng', 'pinyin_eng' => 'sheng', 'meaning_thai' => 'เสียง', 'meaning_english' => 'sound'],
            ['hanzi' => '護', 'pinyin' => 'hù', 'pinyin_eng' => 'hu', 'meaning_thai' => 'ปกป้อง', 'meaning_english' => 'protect'],
            ['hanzi' => '節', 'pinyin' => 'jié', 'pinyin_eng' => 'jie', 'meaning_thai' => 'เทศกาล', 'meaning_english' => 'festival'],
            ['hanzi' => '願', 'pinyin' => 'yuàn', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'ปรารถนา', 'meaning_english' => 'wish'],
            ['hanzi' => '擔', 'pinyin' => 'dān', 'pinyin_eng' => 'dan', 'meaning_thai' => 'แบก', 'meaning_english' => 'carry'],
            ['hanzi' => '壞', 'pinyin' => 'huài', 'pinyin_eng' => 'huai', 'meaning_thai' => 'เลว', 'meaning_english' => 'bad'],
            ['hanzi' => '議', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'สนทนา', 'meaning_english' => 'discuss'],
            ['hanzi' => '禮', 'pinyin' => 'lǐ', 'pinyin_eng' => 'li', 'meaning_thai' => 'ของขวัญ', 'meaning_english' => 'gift'],
            ['hanzi' => '數', 'pinyin' => 'shù', 'pinyin_eng' => 'shu', 'meaning_thai' => 'จำนวน', 'meaning_english' => 'number'],
            ['hanzi' => '調', 'pinyin' => 'tiáo', 'pinyin_eng' => 'tiao', 'meaning_thai' => 'ปรับ', 'meaning_english' => 'adjust'],
            ['hanzi' => '業', 'pinyin' => 'yè', 'pinyin_eng' => 'ye', 'meaning_thai' => 'ธุรกิจ', 'meaning_english' => 'business'],
            ['hanzi' => '參', 'pinyin' => 'cān', 'pinyin_eng' => 'can', 'meaning_thai' => 'เข้าร่วม', 'meaning_english' => 'participate'],
            ['hanzi' => '復', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'กลับ', 'meaning_english' => 'return'],
            ['hanzi' => '據', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ตาม', 'meaning_english' => 'according to'],
            ['hanzi' => '簡', 'pinyin' => 'jiǎn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ง่าย', 'meaning_english' => 'simple'],
            ['hanzi' => '輕', 'pinyin' => 'qīng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'เบา', 'meaning_english' => 'light'],
            ['hanzi' => '滿', 'pinyin' => 'mǎn', 'pinyin_eng' => 'man', 'meaning_thai' => 'เต็ม', 'meaning_english' => 'full'],
            ['hanzi' => '靜', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'เงียบ', 'meaning_english' => 'quiet'],
            ['hanzi' => '極', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'สุดขีด', 'meaning_english' => 'extreme'],
            ['hanzi' => '講', 'pinyin' => 'jiǎng', 'pinyin_eng' => 'jiang', 'meaning_thai' => 'พูด', 'meaning_english' => 'speak'],
            ['hanzi' => '戲', 'pinyin' => 'xì', 'pinyin_eng' => 'xi', 'meaning_thai' => 'เล่น', 'meaning_english' => 'play'],
            ['hanzi' => '終', 'pinyin' => 'zhōng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'จบ', 'meaning_english' => 'end'],
            ['hanzi' => '圖', 'pinyin' => 'tú', 'pinyin_eng' => 'tu', 'meaning_thai' => 'รูปภาพ', 'meaning_english' => 'picture'],
            ['hanzi' => '換', 'pinyin' => 'huàn', 'pinyin_eng' => 'huan', 'meaning_thai' => 'เปลี่ยน', 'meaning_english' => 'change'],
            ['hanzi' => '檢', 'pinyin' => 'jiǎn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ตรวจสอบ', 'meaning_english' => 'check'],
            ['hanzi' => '臉', 'pinyin' => 'liǎn', 'pinyin_eng' => 'lian', 'meaning_thai' => 'ใบหน้า', 'meaning_english' => 'face'],
            ['hanzi' => '擇', 'pinyin' => 'zé', 'pinyin_eng' => 'ze', 'meaning_thai' => 'เลือก', 'meaning_english' => 'choose'],
            ['hanzi' => '樓', 'pinyin' => 'lóu', 'pinyin_eng' => 'lou', 'meaning_thai' => 'อาคาร', 'meaning_english' => 'building'],
            ['hanzi' => '練', 'pinyin' => 'liàn', 'pinyin_eng' => 'lian', 'meaning_thai' => 'ฝึกฝน', 'meaning_english' => 'practice'],
            ['hanzi' => '歷', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'ประวัติศาสตร์', 'meaning_english' => 'history'],
            ['hanzi' => '顧', 'pinyin' => 'gù', 'pinyin_eng' => 'gu', 'meaning_thai' => 'ดูแล', 'meaning_english' => 'take care'],
            ['hanzi' => '畫', 'pinyin' => 'huà', 'pinyin_eng' => 'hua', 'meaning_thai' => 'วาด', 'meaning_english' => 'draw'],
            ['hanzi' => '聞', 'pinyin' => 'wén', 'pinyin_eng' => 'wen', 'meaning_thai' => 'ได้ยิน', 'meaning_english' => 'hear'],
            ['hanzi' => '腳', 'pinyin' => 'jiǎo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'เท้า', 'meaning_english' => 'foot'],
            ['hanzi' => '詞', 'pinyin' => 'cí', 'pinyin_eng' => 'ci', 'meaning_thai' => 'คำ', 'meaning_english' => 'word'],
            ['hanzi' => '輛', 'pinyin' => 'liàng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'ยานพาหนะ', 'meaning_english' => 'vehicle'],
            ['hanzi' => '雙', 'pinyin' => 'shuāng', 'pinyin_eng' => 'shuang', 'meaning_thai' => 'คู่', 'meaning_english' => 'pair'],
            ['hanzi' => '響', 'pinyin' => 'xiǎng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'เสียง', 'meaning_english' => 'sound'],
            ['hanzi' => '網', 'pinyin' => 'wǎng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ตาข่าย', 'meaning_english' => 'net'],
            ['hanzi' => '園', 'pinyin' => 'yuán', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'สวน', 'meaning_english' => 'garden'],
            ['hanzi' => '遲', 'pinyin' => 'chí', 'pinyin_eng' => 'chi', 'meaning_thai' => 'สาย', 'meaning_english' => 'late'],
            ['hanzi' => '燒', 'pinyin' => 'shāo', 'pinyin_eng' => 'shao', 'meaning_thai' => 'เผา', 'meaning_english' => 'burn'],
            ['hanzi' => '聰', 'pinyin' => 'cōng', 'pinyin_eng' => 'cong', 'meaning_thai' => 'ฉลาด', 'meaning_english' => 'intelligent'],
            ['hanzi' => '樹', 'pinyin' => 'shù', 'pinyin_eng' => 'shu', 'meaning_thai' => 'ต้นไม้', 'meaning_english' => 'tree'],
            ['hanzi' => '銀', 'pinyin' => 'yín', 'pinyin_eng' => 'yin', 'meaning_thai' => 'เงิน', 'meaning_english' => 'silver'],
            ['hanzi' => '環', 'pinyin' => 'huán', 'pinyin_eng' => 'huan', 'meaning_thai' => 'แหวน', 'meaning_english' => 'ring'],
            ['hanzi' => '爺', 'pinyin' => 'yé', 'pinyin_eng' => 'ye', 'meaning_thai' => 'ปู่', 'meaning_english' => 'grandpa'],
            ['hanzi' => '燈', 'pinyin' => 'dēng', 'pinyin_eng' => 'deng', 'meaning_thai' => 'โคมไฟ', 'meaning_english' => 'lamp'],
            ['hanzi' => '褲', 'pinyin' => 'kù', 'pinyin_eng' => 'ku', 'meaning_thai' => 'กางเกง', 'meaning_english' => 'pants'],
            ['hanzi' => '盤', 'pinyin' => 'pán', 'pinyin_eng' => 'pan', 'meaning_thai' => 'จาน', 'meaning_english' => 'plate'],
            ['hanzi' => '陽', 'pinyin' => 'yáng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'ดวงอาทิตย์', 'meaning_english' => 'sun'],
            ['hanzi' => '較', 'pinyin' => 'jiào', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'เปรียบเทียบ', 'meaning_english' => 'compare'],
            ['hanzi' => '層', 'pinyin' => 'céng', 'pinyin_eng' => 'ceng', 'meaning_thai' => 'ชั้น', 'meaning_english' => 'layer'],
            ['hanzi' => '鐵', 'pinyin' => 'tiě', 'pinyin_eng' => 'tie', 'meaning_thai' => 'เหล็ก', 'meaning_english' => 'iron'],
            ['hanzi' => '舊', 'pinyin' => 'jiù', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'เก่า', 'meaning_english' => 'old'],
            ['hanzi' => '藍', 'pinyin' => 'lán', 'pinyin_eng' => 'lan', 'meaning_thai' => 'สีน้ำเงิน', 'meaning_english' => 'blue'],
            ['hanzi' => '騎', 'pinyin' => 'qí', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ขี่', 'meaning_english' => 'ride'],
            ['hanzi' => '餓', 'pinyin' => 'è', 'pinyin_eng' => 'e', 'meaning_thai' => 'หิว', 'meaning_english' => 'hungry'],
            ['hanzi' => '淨', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'สะอาด', 'meaning_english' => 'clean'],
            ['hanzi' => '鮮', 'pinyin' => 'xiān', 'pinyin_eng' => 'xian', 'meaning_thai' => 'สด', 'meaning_english' => 'fresh'],
            ['hanzi' => '掃', 'pinyin' => 'sǎo', 'pinyin_eng' => 'sao', 'meaning_thai' => 'กวาด', 'meaning_english' => 'sweep'],
            ['hanzi' => '慣', 'pinyin' => 'guàn', 'pinyin_eng' => 'guan', 'meaning_thai' => 'เคยชิน', 'meaning_english' => 'accustomed'],
            ['hanzi' => '郵', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'ไปรษณีย์', 'meaning_english' => 'post'],
            ['hanzi' => '綠', 'pinyin' => 'lǜ', 'pinyin_eng' => 'lv', 'meaning_thai' => 'สีเขียว', 'meaning_english' => 'green'],
            ['hanzi' => '鄰', 'pinyin' => 'lín', 'pinyin_eng' => 'lin', 'meaning_thai' => 'เพื่อนบ้าน', 'meaning_english' => 'neighbor'],
            ['hanzi' => '飲', 'pinyin' => 'yǐn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'ดื่ม', 'meaning_english' => 'drink'],
            ['hanzi' => '襯', 'pinyin' => 'chèn', 'pinyin_eng' => 'chen', 'meaning_thai' => 'ซับใน', 'meaning_english' => 'lining'],
            ['hanzi' => '績', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ความสำเร็จ', 'meaning_english' => 'achievement'],
            ['hanzi' => '煉', 'pinyin' => 'liàn', 'pinyin_eng' => 'lian', 'meaning_thai' => 'กลั่น', 'meaning_english' => 'refine'],
            ['hanzi' => '傘', 'pinyin' => 'sǎn', 'pinyin_eng' => 'san', 'meaning_thai' => 'ร่ม', 'meaning_english' => 'umbrella'],
            ['hanzi' => '飽', 'pinyin' => 'bǎo', 'pinyin_eng' => 'bao', 'meaning_thai' => 'เต็ม', 'meaning_english' => 'full'],
            ['hanzi' => '鍛', 'pinyin' => 'duàn', 'pinyin_eng' => 'duan', 'meaning_thai' => 'ปลอม', 'meaning_english' => 'forge'],
            ['hanzi' => '夾', 'pinyin' => 'jiā', 'pinyin_eng' => 'jia', 'meaning_thai' => 'กดจากทั้งสองด้าน', 'meaning_english' => 'press from both sides'],
            ['hanzi' => '烏', 'pinyin' => 'wū', 'pinyin_eng' => 'wu', 'meaning_thai' => 'อีกา', 'meaning_english' => 'crow'],
        ]);

        // hanzi_categories Traditional Hanzi (236)
        DB::table('hanzi_categories')->insert([
            ['hanzi_id' => 7001, 'category_id' => 9],
            ['hanzi_id' => 7002, 'category_id' => 9],
            ['hanzi_id' => 7003, 'category_id' => 9],
            ['hanzi_id' => 7004, 'category_id' => 9],
            ['hanzi_id' => 7005, 'category_id' => 9],
            ['hanzi_id' => 7006, 'category_id' => 9],
            ['hanzi_id' => 7007, 'category_id' => 9],
            ['hanzi_id' => 7008, 'category_id' => 9],
            ['hanzi_id' => 7009, 'category_id' => 9],
            ['hanzi_id' => 7010, 'category_id' => 9],
            ['hanzi_id' => 7011, 'category_id' => 9],
            ['hanzi_id' => 7012, 'category_id' => 9],
            ['hanzi_id' => 7013, 'category_id' => 9],
            ['hanzi_id' => 7014, 'category_id' => 9],
            ['hanzi_id' => 7015, 'category_id' => 9],
            ['hanzi_id' => 7016, 'category_id' => 9],
            ['hanzi_id' => 7017, 'category_id' => 9],
            ['hanzi_id' => 7018, 'category_id' => 9],
            ['hanzi_id' => 7019, 'category_id' => 9],
            ['hanzi_id' => 7020, 'category_id' => 9],
            ['hanzi_id' => 7021, 'category_id' => 9],
            ['hanzi_id' => 7022, 'category_id' => 9],
            ['hanzi_id' => 7023, 'category_id' => 9],
            ['hanzi_id' => 7024, 'category_id' => 9],
            ['hanzi_id' => 7025, 'category_id' => 9],
            ['hanzi_id' => 7026, 'category_id' => 9],
            ['hanzi_id' => 7027, 'category_id' => 9],
            ['hanzi_id' => 7028, 'category_id' => 9],
            ['hanzi_id' => 7029, 'category_id' => 9],
            ['hanzi_id' => 7030, 'category_id' => 9],
            ['hanzi_id' => 7031, 'category_id' => 9],
            ['hanzi_id' => 7032, 'category_id' => 9],
            ['hanzi_id' => 7033, 'category_id' => 9],
            ['hanzi_id' => 7034, 'category_id' => 9],
            ['hanzi_id' => 7035, 'category_id' => 9],
            ['hanzi_id' => 7036, 'category_id' => 9],
            ['hanzi_id' => 7037, 'category_id' => 9],
            ['hanzi_id' => 7038, 'category_id' => 9],
            ['hanzi_id' => 7039, 'category_id' => 9],
            ['hanzi_id' => 7040, 'category_id' => 9],
            ['hanzi_id' => 7041, 'category_id' => 9],
            ['hanzi_id' => 7042, 'category_id' => 9],
            ['hanzi_id' => 7043, 'category_id' => 9],
            ['hanzi_id' => 7044, 'category_id' => 9],
            ['hanzi_id' => 7045, 'category_id' => 9],
            ['hanzi_id' => 7046, 'category_id' => 9],
            ['hanzi_id' => 7047, 'category_id' => 9],
            ['hanzi_id' => 7048, 'category_id' => 9],
            ['hanzi_id' => 7049, 'category_id' => 9],
            ['hanzi_id' => 7050, 'category_id' => 9],
            ['hanzi_id' => 7051, 'category_id' => 9],
            ['hanzi_id' => 7052, 'category_id' => 9],
            ['hanzi_id' => 7053, 'category_id' => 9],
            ['hanzi_id' => 7054, 'category_id' => 9],
            ['hanzi_id' => 7055, 'category_id' => 9],
            ['hanzi_id' => 7056, 'category_id' => 9],
            ['hanzi_id' => 7057, 'category_id' => 9],
            ['hanzi_id' => 7058, 'category_id' => 9],
            ['hanzi_id' => 7059, 'category_id' => 9],
            ['hanzi_id' => 7060, 'category_id' => 9],
            ['hanzi_id' => 7061, 'category_id' => 9],
            ['hanzi_id' => 7062, 'category_id' => 9],
            ['hanzi_id' => 7063, 'category_id' => 9],
            ['hanzi_id' => 7064, 'category_id' => 9],
            ['hanzi_id' => 7065, 'category_id' => 9],
            ['hanzi_id' => 7066, 'category_id' => 9],
            ['hanzi_id' => 7067, 'category_id' => 9],
            ['hanzi_id' => 7068, 'category_id' => 9],
            ['hanzi_id' => 7069, 'category_id' => 9],
            ['hanzi_id' => 7070, 'category_id' => 9],
            ['hanzi_id' => 7071, 'category_id' => 9],
            ['hanzi_id' => 7072, 'category_id' => 9],
            ['hanzi_id' => 7073, 'category_id' => 9],
            ['hanzi_id' => 7074, 'category_id' => 9],
            ['hanzi_id' => 7075, 'category_id' => 9],
            ['hanzi_id' => 7076, 'category_id' => 9],
            ['hanzi_id' => 7077, 'category_id' => 9],
            ['hanzi_id' => 7078, 'category_id' => 9],
            ['hanzi_id' => 7079, 'category_id' => 9],
            ['hanzi_id' => 7080, 'category_id' => 9],
            ['hanzi_id' => 7081, 'category_id' => 9],
            ['hanzi_id' => 7082, 'category_id' => 9],
            ['hanzi_id' => 7083, 'category_id' => 9],
            ['hanzi_id' => 7084, 'category_id' => 9],
            ['hanzi_id' => 7085, 'category_id' => 9],
            ['hanzi_id' => 7086, 'category_id' => 9],
            ['hanzi_id' => 7087, 'category_id' => 9],
            ['hanzi_id' => 7088, 'category_id' => 9],
            ['hanzi_id' => 7089, 'category_id' => 9],
            ['hanzi_id' => 7090, 'category_id' => 9],
            ['hanzi_id' => 7091, 'category_id' => 9],
            ['hanzi_id' => 7092, 'category_id' => 9],
            ['hanzi_id' => 7093, 'category_id' => 9],
            ['hanzi_id' => 7094, 'category_id' => 9],
            ['hanzi_id' => 7095, 'category_id' => 9],
            ['hanzi_id' => 7096, 'category_id' => 9],
            ['hanzi_id' => 7097, 'category_id' => 9],
            ['hanzi_id' => 7098, 'category_id' => 9],
            ['hanzi_id' => 7099, 'category_id' => 9],
            ['hanzi_id' => 7100, 'category_id' => 9],
            ['hanzi_id' => 7101, 'category_id' => 9],
            ['hanzi_id' => 7102, 'category_id' => 9],
            ['hanzi_id' => 7103, 'category_id' => 9],
            ['hanzi_id' => 7104, 'category_id' => 9],
            ['hanzi_id' => 7105, 'category_id' => 9],
            ['hanzi_id' => 7106, 'category_id' => 9],
            ['hanzi_id' => 7107, 'category_id' => 9],
            ['hanzi_id' => 7108, 'category_id' => 9],
            ['hanzi_id' => 7109, 'category_id' => 9],
            ['hanzi_id' => 7110, 'category_id' => 9],
            ['hanzi_id' => 7111, 'category_id' => 9],
            ['hanzi_id' => 7112, 'category_id' => 9],
            ['hanzi_id' => 7113, 'category_id' => 9],
            ['hanzi_id' => 7114, 'category_id' => 9],
            ['hanzi_id' => 7115, 'category_id' => 9],
            ['hanzi_id' => 7116, 'category_id' => 9],
            ['hanzi_id' => 7117, 'category_id' => 9],
            ['hanzi_id' => 7118, 'category_id' => 9],
            ['hanzi_id' => 7119, 'category_id' => 9],
            ['hanzi_id' => 7120, 'category_id' => 9],
            ['hanzi_id' => 7121, 'category_id' => 9],
            ['hanzi_id' => 7122, 'category_id' => 9],
            ['hanzi_id' => 7123, 'category_id' => 9],
            ['hanzi_id' => 7124, 'category_id' => 9],
            ['hanzi_id' => 7125, 'category_id' => 9],
            ['hanzi_id' => 7126, 'category_id' => 9],
            ['hanzi_id' => 7127, 'category_id' => 9],
            ['hanzi_id' => 7128, 'category_id' => 9],
            ['hanzi_id' => 7129, 'category_id' => 9],
            ['hanzi_id' => 7130, 'category_id' => 9],
            ['hanzi_id' => 7131, 'category_id' => 9],
            ['hanzi_id' => 7132, 'category_id' => 9],
            ['hanzi_id' => 7133, 'category_id' => 9],
            ['hanzi_id' => 7134, 'category_id' => 9],
            ['hanzi_id' => 7135, 'category_id' => 9],
            ['hanzi_id' => 7136, 'category_id' => 9],
            ['hanzi_id' => 7137, 'category_id' => 9],
            ['hanzi_id' => 7138, 'category_id' => 9],
            ['hanzi_id' => 7139, 'category_id' => 9],
            ['hanzi_id' => 7140, 'category_id' => 9],
            ['hanzi_id' => 7141, 'category_id' => 9],
            ['hanzi_id' => 7142, 'category_id' => 9],
            ['hanzi_id' => 7143, 'category_id' => 9],
            ['hanzi_id' => 7144, 'category_id' => 9],
            ['hanzi_id' => 7145, 'category_id' => 9],
            ['hanzi_id' => 7146, 'category_id' => 9],
            ['hanzi_id' => 7147, 'category_id' => 9],
            ['hanzi_id' => 7148, 'category_id' => 9],
            ['hanzi_id' => 7149, 'category_id' => 9],
            ['hanzi_id' => 7150, 'category_id' => 9],
            ['hanzi_id' => 7151, 'category_id' => 9],
            ['hanzi_id' => 7152, 'category_id' => 9],
            ['hanzi_id' => 7153, 'category_id' => 9],
            ['hanzi_id' => 7154, 'category_id' => 9],
            ['hanzi_id' => 7155, 'category_id' => 9],
            ['hanzi_id' => 7156, 'category_id' => 9],
            ['hanzi_id' => 7157, 'category_id' => 9],
            ['hanzi_id' => 7158, 'category_id' => 9],
            ['hanzi_id' => 7159, 'category_id' => 9],
            ['hanzi_id' => 7160, 'category_id' => 9],
            ['hanzi_id' => 7161, 'category_id' => 9],
            ['hanzi_id' => 7162, 'category_id' => 9],
            ['hanzi_id' => 7163, 'category_id' => 9],
            ['hanzi_id' => 7164, 'category_id' => 9],
            ['hanzi_id' => 7165, 'category_id' => 9],
            ['hanzi_id' => 7166, 'category_id' => 9],
            ['hanzi_id' => 7167, 'category_id' => 9],
            ['hanzi_id' => 7168, 'category_id' => 9],
            ['hanzi_id' => 7169, 'category_id' => 9],
            ['hanzi_id' => 7170, 'category_id' => 9],
            ['hanzi_id' => 7171, 'category_id' => 9],
            ['hanzi_id' => 7172, 'category_id' => 9],
            ['hanzi_id' => 7173, 'category_id' => 9],
            ['hanzi_id' => 7174, 'category_id' => 9],
            ['hanzi_id' => 7175, 'category_id' => 9],
            ['hanzi_id' => 7176, 'category_id' => 9],
            ['hanzi_id' => 7177, 'category_id' => 9],
            ['hanzi_id' => 7178, 'category_id' => 9],
            ['hanzi_id' => 7179, 'category_id' => 9],
            ['hanzi_id' => 7180, 'category_id' => 9],
            ['hanzi_id' => 7181, 'category_id' => 9],
            ['hanzi_id' => 7182, 'category_id' => 9],
            ['hanzi_id' => 7183, 'category_id' => 9],
            ['hanzi_id' => 7184, 'category_id' => 9],
            ['hanzi_id' => 7185, 'category_id' => 9],
            ['hanzi_id' => 7186, 'category_id' => 9],
            ['hanzi_id' => 7187, 'category_id' => 9],
            ['hanzi_id' => 7188, 'category_id' => 9],
            ['hanzi_id' => 7189, 'category_id' => 9],
            ['hanzi_id' => 7190, 'category_id' => 9],
            ['hanzi_id' => 7191, 'category_id' => 9],
            ['hanzi_id' => 7192, 'category_id' => 9],
            ['hanzi_id' => 7193, 'category_id' => 9],
            ['hanzi_id' => 7194, 'category_id' => 9],
            ['hanzi_id' => 7195, 'category_id' => 9],
            ['hanzi_id' => 7196, 'category_id' => 9],
            ['hanzi_id' => 7197, 'category_id' => 9],
            ['hanzi_id' => 7198, 'category_id' => 9],
            ['hanzi_id' => 7199, 'category_id' => 9],
            ['hanzi_id' => 7200, 'category_id' => 9],
            ['hanzi_id' => 7201, 'category_id' => 9],
            ['hanzi_id' => 7202, 'category_id' => 9],
            ['hanzi_id' => 7203, 'category_id' => 9],
            ['hanzi_id' => 7204, 'category_id' => 9],
            ['hanzi_id' => 7205, 'category_id' => 9],
            ['hanzi_id' => 7206, 'category_id' => 9],
            ['hanzi_id' => 7207, 'category_id' => 9],
            ['hanzi_id' => 7208, 'category_id' => 9],
            ['hanzi_id' => 7209, 'category_id' => 9],
            ['hanzi_id' => 7210, 'category_id' => 9],
            ['hanzi_id' => 7211, 'category_id' => 9],
            ['hanzi_id' => 7212, 'category_id' => 9],
            ['hanzi_id' => 7213, 'category_id' => 9],
            ['hanzi_id' => 7214, 'category_id' => 9],
            ['hanzi_id' => 7215, 'category_id' => 9],
            ['hanzi_id' => 7216, 'category_id' => 9],
            ['hanzi_id' => 7217, 'category_id' => 9],
            ['hanzi_id' => 7218, 'category_id' => 9],
            ['hanzi_id' => 7219, 'category_id' => 9],
            ['hanzi_id' => 7220, 'category_id' => 9],
            ['hanzi_id' => 7221, 'category_id' => 9],
            ['hanzi_id' => 7222, 'category_id' => 9],
            ['hanzi_id' => 7223, 'category_id' => 9],
            ['hanzi_id' => 7224, 'category_id' => 9],
            ['hanzi_id' => 7225, 'category_id' => 9],
            ['hanzi_id' => 7226, 'category_id' => 9],
            ['hanzi_id' => 7227, 'category_id' => 9],
            ['hanzi_id' => 7228, 'category_id' => 9],
            ['hanzi_id' => 7229, 'category_id' => 9],
            ['hanzi_id' => 7230, 'category_id' => 9],
            ['hanzi_id' => 7231, 'category_id' => 9],
            ['hanzi_id' => 7232, 'category_id' => 9],
            ['hanzi_id' => 7233, 'category_id' => 9],
            ['hanzi_id' => 7234, 'category_id' => 9],
            ['hanzi_id' => 7235, 'category_id' => 9],
            ['hanzi_id' => 7236, 'category_id' => 9],
        ]);
    }
}
