<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HanziHSK3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // hanzi HSK 3 (270)
        DB::table('hanzi')->insert([
            ['hanzi' => '啊', 'pinyin' => 'a', 'pinyin_eng' => 'a', 'meaning_thai' => 'อะ, โอ', 'meaning_english' => 'ah, oh'],
            ['hanzi' => '把', 'pinyin' => 'bǎ', 'pinyin_eng' => 'ba', 'meaning_thai' => 'จับ', 'meaning_english' => 'handle, grasp'],
            ['hanzi' => '只', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'เท่านั้น', 'meaning_english' => 'only'],
            ['hanzi' => '如', 'pinyin' => 'rú', 'pinyin_eng' => 'ru', 'meaning_thai' => 'เหมือน', 'meaning_english' => 'like, as'],
            ['hanzi' => '自', 'pinyin' => 'zì', 'pinyin_eng' => 'zi', 'meaning_thai' => 'ตัวเอง', 'meaning_english' => 'self, from'],
            ['hanzi' => '发', 'pinyin' => 'fā', 'pinyin_eng' => 'fa', 'meaning_thai' => 'ส่ง, ผม', 'meaning_english' => 'send, hair'],
            ['hanzi' => '心', 'pinyin' => 'xīn', 'pinyin_eng' => 'xin', 'meaning_thai' => 'หัวใจ, จิตใจ', 'meaning_english' => 'heart, mind'],
            ['hanzi' => '定', 'pinyin' => 'dìng', 'pinyin_eng' => 'ding', 'meaning_thai' => 'ตัดสินใจ, แก้ไข', 'meaning_english' => 'decide, fix'],
            ['hanzi' => '该', 'pinyin' => 'gāi', 'pinyin_eng' => 'gai', 'meaning_thai' => 'ควร', 'meaning_english' => 'should, ought to'],
            ['hanzi' => '当', 'pinyin' => 'dāng', 'pinyin_eng' => 'dang', 'meaning_thai' => 'เมื่อ, เหมาะสม', 'meaning_english' => 'when, appropriate'],
            ['hanzi' => '用', 'pinyin' => 'yòng', 'pinyin_eng' => 'yong', 'meaning_thai' => 'ใช้', 'meaning_english' => 'use'],
            ['hanzi' => '地', 'pinyin' => 'dì', 'pinyin_eng' => 'di', 'meaning_thai' => 'ดิน', 'meaning_english' => 'earth, ground'],
            ['hanzi' => '行', 'pinyin' => 'xíng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'เดินทาง', 'meaning_english' => 'walk, travel'],
            ['hanzi' => '而', 'pinyin' => 'ér', 'pinyin_eng' => 'er', 'meaning_thai' => 'และ, แต่', 'meaning_english' => 'and, but'],
            ['hanzi' => '像', 'pinyin' => 'xiàng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'เหมือน', 'meaning_english' => 'like, resemble'],
            ['hanzi' => '被', 'pinyin' => 'bèi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'ถูก', 'meaning_english' => 'by (passive voice)'],
            ['hanzi' => '跟', 'pinyin' => 'gēn', 'pinyin_eng' => 'gen', 'meaning_thai' => 'กับ, ตาม', 'meaning_english' => 'with, follow'],
            ['hanzi' => '成', 'pinyin' => 'chéng', 'pinyin_eng' => 'cheng', 'meaning_thai' => 'กลายเป็น, ประสบความสำเร็จ', 'meaning_english' => 'become, succeed'],
            ['hanzi' => '感', 'pinyin' => 'gǎn', 'pinyin_eng' => 'gan', 'meaning_thai' => 'รู้สึก', 'meaning_english' => 'feel, sense'],
            ['hanzi' => '干', 'pinyin' => 'gàn', 'pinyin_eng' => 'gan', 'meaning_thai' => 'ทำ, แห้ง', 'meaning_english' => 'do, dry'],
            ['hanzi' => '法', 'pinyin' => 'fǎ', 'pinyin_eng' => 'fa', 'meaning_thai' => 'กฎหมาย, วิธีการ', 'meaning_english' => 'law, method'],
            ['hanzi' => '己', 'pinyin' => 'jǐ', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ตัวเอง', 'meaning_english' => 'self, oneself'],
            ['hanzi' => '信', 'pinyin' => 'xìn', 'pinyin_eng' => 'xin', 'meaning_thai' => 'เชื่อ, จดหมาย', 'meaning_english' => 'trust, letter'],
            ['hanzi' => '实', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'จริง', 'meaning_english' => 'real, true'],
            ['hanzi' => '方', 'pinyin' => 'fāng', 'pinyin_eng' => 'fang', 'meaning_thai' => 'สี่เหลี่ยม, ทิศทาง', 'meaning_english' => 'square, direction'],
            ['hanzi' => '应', 'pinyin' => 'yīng', 'pinyin_eng' => 'ying', 'meaning_thai' => 'ควร, ตอบสนอง', 'meaning_english' => 'should, respond'],
            ['hanzi' => '头', 'pinyin' => 'tóu', 'pinyin_eng' => 'tou', 'meaning_thai' => 'หัว', 'meaning_english' => 'head'],
            ['hanzi' => '特', 'pinyin' => 'tè', 'pinyin_eng' => 'te', 'meaning_thai' => 'พิเศษ', 'meaning_english' => 'special'],
            ['hanzi' => '相', 'pinyin' => 'xiāng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'ซึ่งกันและกัน', 'meaning_english' => 'mutual, each other'],
            ['hanzi' => '需', 'pinyin' => 'xū', 'pinyin_eng' => 'xu', 'meaning_thai' => 'ต้องการ', 'meaning_english' => 'need'],
            ['hanzi' => '放', 'pinyin' => 'fàng', 'pinyin_eng' => 'fang', 'meaning_thai' => 'ปล่อย, วาง', 'meaning_english' => 'release, put'],
            ['hanzi' => '直', 'pinyin' => 'zhí', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ตรง', 'meaning_english' => 'straight, direct'],
            ['hanzi' => '才', 'pinyin' => 'cái', 'pinyin_eng' => 'cai', 'meaning_thai' => 'พรสวรรค์, เพิ่ง', 'meaning_english' => 'talent, just now'],
            ['hanzi' => '于', 'pinyin' => 'yú', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ที่, ไปยัง', 'meaning_english' => 'at, to'],
            ['hanzi' => '带', 'pinyin' => 'dài', 'pinyin_eng' => 'dai', 'meaning_thai' => 'นำ, เข็มขัด', 'meaning_english' => 'bring, belt'],
            ['hanzi' => '力', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'พลัง', 'meaning_english' => 'power, force'],
            ['hanzi' => '种', 'pinyin' => 'zhǒng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'ชนิด, ประเภท', 'meaning_english' => 'kind, type'],
            ['hanzi' => '者', 'pinyin' => 'zhě', 'pinyin_eng' => 'zhe', 'meaning_thai' => 'คน', 'meaning_english' => 'person'],
            ['hanzi' => '安', 'pinyin' => 'ān', 'pinyin_eng' => 'an', 'meaning_thai' => 'ความสงบ, ปลอดภัย', 'meaning_english' => 'peace, safe'],
            ['hanzi' => '理', 'pinyin' => 'lǐ', 'pinyin_eng' => 'li', 'meaning_thai' => 'เหตุผล, จัดการ', 'meaning_english' => 'reason, manage'],
            ['hanzi' => '重', 'pinyin' => 'zhòng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'หนัก, สำคัญ', 'meaning_english' => 'heavy, important'],
            ['hanzi' => '记', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'จำ, บันทึก', 'meaning_english' => 'remember, record'],
            ['hanzi' => '加', 'pinyin' => 'jiā', 'pinyin_eng' => 'jia', 'meaning_thai' => 'เพิ่ม', 'meaning_english' => 'add, increase'],
            ['hanzi' => '接', 'pinyin' => 'jiē', 'pinyin_eng' => 'jie', 'meaning_thai' => 'รับ, เชื่อมต่อ', 'meaning_english' => 'receive, connect'],
            ['hanzi' => '拿', 'pinyin' => 'ná', 'pinyin_eng' => 'na', 'meaning_thai' => 'เอา, ถือ', 'meaning_english' => 'take, hold'],
            ['hanzi' => '解', 'pinyin' => 'jiě', 'pinyin_eng' => 'jie', 'meaning_thai' => 'แก้ปัญหา, อธิบาย', 'meaning_english' => 'solve, explain'],
            ['hanzi' => '其', 'pinyin' => 'qí', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ของมัน, ของพวกเขา', 'meaning_english' => 'its, their'],
            ['hanzi' => '又', 'pinyin' => 'yòu', 'pinyin_eng' => 'you', 'meaning_thai' => 'อีกครั้ง, เช่นกัน', 'meaning_english' => 'again, also'],
            ['hanzi' => '更', 'pinyin' => 'gèng', 'pinyin_eng' => 'geng', 'meaning_thai' => 'มากกว่า, เปลี่ยน', 'meaning_english' => 'more, change'],
            ['hanzi' => '马', 'pinyin' => 'mǎ', 'pinyin_eng' => 'ma', 'meaning_thai' => 'ม้า', 'meaning_english' => 'horse'],
            ['hanzi' => '结', 'pinyin' => 'jié', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ผูก, ปม', 'meaning_english' => 'tie, knot'],
            ['hanzi' => '难', 'pinyin' => 'nán', 'pinyin_eng' => 'nan', 'meaning_thai' => 'ยาก', 'meaning_english' => 'difficult, hard'],
            ['hanzi' => '位', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'ตำแหน่ง, สถานที่', 'meaning_english' => 'position, place'],
            ['hanzi' => '刚', 'pinyin' => 'gāng', 'pinyin_eng' => 'gang', 'meaning_thai' => 'เพิ่ง, แข็ง', 'meaning_english' => 'just, firm'],
            ['hanzi' => '查', 'pinyin' => 'chá', 'pinyin_eng' => 'cha', 'meaning_thai' => 'ตรวจสอบ', 'meaning_english' => 'check, examine'],
            ['hanzi' => '或', 'pinyin' => 'huò', 'pinyin_eng' => 'huo', 'meaning_thai' => 'หรือ', 'meaning_english' => 'or'],
            ['hanzi' => '变', 'pinyin' => 'biàn', 'pinyin_eng' => 'bian', 'meaning_thai' => 'เปลี่ยน', 'meaning_english' => 'change, become'],
            ['hanzi' => '物', 'pinyin' => 'wù', 'pinyin_eng' => 'wu', 'meaning_thai' => 'สิ่งของ, วัตถุ', 'meaning_english' => 'thing, object'],
            ['hanzi' => '总', 'pinyin' => 'zǒng', 'pinyin_eng' => 'zong', 'meaning_thai' => 'รวม, ทั่วไป', 'meaning_english' => 'total, general'],
            ['hanzi' => '办', 'pinyin' => 'bàn', 'pinyin_eng' => 'ban', 'meaning_thai' => 'จัดการ, ทำ', 'meaning_english' => 'handle, do'],
            ['hanzi' => '主', 'pinyin' => 'zhǔ', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'นาย, หลัก', 'meaning_english' => 'master, main'],
            ['hanzi' => '算', 'pinyin' => 'suàn', 'pinyin_eng' => 'suan', 'meaning_thai' => 'คำนวณ, นับ', 'meaning_english' => 'calculate, count'],
            ['hanzi' => '必', 'pinyin' => 'bì', 'pinyin_eng' => 'bi', 'meaning_thai' => 'ต้อง, จำเป็น', 'meaning_english' => 'must, necessary'],
            ['hanzi' => '害', 'pinyin' => 'hài', 'pinyin_eng' => 'hai', 'meaning_thai' => 'อันตราย, ทำร้าย', 'meaning_english' => 'harm, injure'],
            ['hanzi' => '选', 'pinyin' => 'xuǎn', 'pinyin_eng' => 'xuan', 'meaning_thai' => 'เลือก', 'meaning_english' => 'choose, select'],
            ['hanzi' => '且', 'pinyin' => 'qiě', 'pinyin_eng' => 'qie', 'meaning_thai' => 'ยิ่งไปกว่านั้น', 'meaning_english' => 'moreover, and'],
            ['hanzi' => '向', 'pinyin' => 'xiàng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'ไปทาง, ทิศทาง', 'meaning_english' => 'towards, direction'],
            ['hanzi' => '照', 'pinyin' => 'zhào', 'pinyin_eng' => 'zhao', 'meaning_thai' => 'ส่องแสง, ถ่ายภาพ', 'meaning_english' => 'shine, photograph'],
            ['hanzi' => '提', 'pinyin' => 'tí', 'pinyin_eng' => 'ti', 'meaning_thai' => 'ถือ, ยก', 'meaning_english' => 'carry, raise'],
            ['hanzi' => '决', 'pinyin' => 'jué', 'pinyin_eng' => 'jue', 'meaning_thai' => 'ตัดสินใจ', 'meaning_english' => 'decide'],
            ['hanzi' => '求', 'pinyin' => 'qiú', 'pinyin_eng' => 'qiu', 'meaning_thai' => 'หา, ขอ', 'meaning_english' => 'seek, request'],
            ['hanzi' => '目', 'pinyin' => 'mù', 'pinyin_eng' => 'mu', 'meaning_thai' => 'ตา, รายการ', 'meaning_english' => 'eye, item'],
            ['hanzi' => '留', 'pinyin' => 'liú', 'pinyin_eng' => 'liu', 'meaning_thai' => 'พัก, ยังคง', 'meaning_english' => 'stay, remain'],
            ['hanzi' => '清', 'pinyin' => 'qīng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'ชัดเจน, สะอาด', 'meaning_english' => 'clear, clean'],
            ['hanzi' => '世', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'โลก, รุ่น', 'meaning_english' => 'world, generation'],
            ['hanzi' => '片', 'pinyin' => 'piàn', 'pinyin_eng' => 'pian', 'meaning_thai' => 'ชิ้น', 'meaning_english' => 'slice, piece'],
            ['hanzi' => '口', 'pinyin' => 'kǒu', 'pinyin_eng' => 'kou', 'meaning_thai' => 'ปาก', 'meaning_english' => 'mouth'],
            ['hanzi' => '酒', 'pinyin' => 'jiǔ', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'แอลกอฮอล์, ไวน์', 'meaning_english' => 'alcohol, wine'],
            ['hanzi' => '周', 'pinyin' => 'zhōu', 'pinyin_eng' => 'zhou', 'meaning_thai' => 'สัปดาห์, วงจร', 'meaning_english' => 'week, cycle'],
            ['hanzi' => '赛', 'pinyin' => 'sài', 'pinyin_eng' => 'sai', 'meaning_thai' => 'การแข่งขัน', 'meaning_english' => 'match, competition'],
            ['hanzi' => '须', 'pinyin' => 'xū', 'pinyin_eng' => 'xu', 'meaning_thai' => 'ต้อง, หนวด', 'meaning_english' => 'must, beard'],
            ['hanzi' => '卡', 'pinyin' => 'kǎ', 'pinyin_eng' => 'ka', 'meaning_thai' => 'การ์ด', 'meaning_english' => 'card'],
            ['hanzi' => '婚', 'pinyin' => 'hūn', 'pinyin_eng' => 'hun', 'meaning_thai' => 'การแต่งงาน', 'meaning_english' => 'marriage'],
            ['hanzi' => '根', 'pinyin' => 'gēn', 'pinyin_eng' => 'gen', 'meaning_thai' => 'ราก, ฐาน', 'meaning_english' => 'root, basis'],
            ['hanzi' => '单', 'pinyin' => 'dān', 'pinyin_eng' => 'dan', 'meaning_thai' => 'เดี่ยว, รายการ', 'meaning_english' => 'single, list'],
            ['hanzi' => '张', 'pinyin' => 'zhāng', 'pinyin_eng' => 'zhang', 'meaning_thai' => 'หน่วยนับของวัตถุแบน, เปิด', 'meaning_english' => 'measure word for flat objects, open'],
            ['hanzi' => '万', 'pinyin' => 'wàn', 'pinyin_eng' => 'wan', 'meaning_thai' => 'หมื่น', 'meaning_english' => 'ten thousand'],
            ['hanzi' => '声', 'pinyin' => 'shēng', 'pinyin_eng' => 'sheng', 'meaning_thai' => 'เสียง', 'meaning_english' => 'sound, voice'],
            ['hanzi' => '音', 'pinyin' => 'yīn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'เสียง, โทน', 'meaning_english' => 'sound, tone'],
            ['hanzi' => '奇', 'pinyin' => 'qí', 'pinyin_eng' => 'qi', 'meaning_thai' => 'แปลก, หายาก', 'meaning_english' => 'strange, rare'],
            ['hanzi' => '怕', 'pinyin' => 'pà', 'pinyin_eng' => 'pa', 'meaning_thai' => 'กลัว', 'meaning_english' => 'fear'],
            ['hanzi' => '护', 'pinyin' => 'hù', 'pinyin_eng' => 'hu', 'meaning_thai' => 'ปกป้อง', 'meaning_english' => 'protect'],
            ['hanzi' => '花', 'pinyin' => 'huā', 'pinyin_eng' => 'hua', 'meaning_thai' => 'ดอกไม้', 'meaning_english' => 'flower'],
            ['hanzi' => '节', 'pinyin' => 'jié', 'pinyin_eng' => 'jie', 'meaning_thai' => 'เทศกาล, ส่วน', 'meaning_english' => 'festival, section'],
            ['hanzi' => '怪', 'pinyin' => 'guài', 'pinyin_eng' => 'guai', 'meaning_thai' => 'แปลก, ตำหนิ', 'meaning_english' => 'strange, blame'],
            ['hanzi' => '愿', 'pinyin' => 'yuàn', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'ยินดี, ปรารถนา', 'meaning_english' => 'willing, wish'],
            ['hanzi' => '除', 'pinyin' => 'chú', 'pinyin_eng' => 'chu', 'meaning_thai' => 'ยกเว้น, ลบ', 'meaning_english' => 'except, remove'],
            ['hanzi' => '界', 'pinyin' => 'jiè', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ขอบเขต, โลก', 'meaning_english' => 'boundary, world'],
            ['hanzi' => '担', 'pinyin' => 'dān', 'pinyin_eng' => 'dan', 'meaning_thai' => 'ถือ, ไหล่', 'meaning_english' => 'carry, shoulder'],
            ['hanzi' => '空', 'pinyin' => 'kōng', 'pinyin_eng' => 'kong', 'meaning_thai' => 'ว่างเปล่า, ท้องฟ้า', 'meaning_english' => 'empty, sky'],
            ['hanzi' => '阿', 'pinyin' => 'ā', 'pinyin_eng' => 'a', 'meaning_thai' => 'คำนำหน้า, อุทาน', 'meaning_english' => 'prefix used before names, an exclamation'],
            ['hanzi' => '注', 'pinyin' => 'zhù', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'เท, หมายเหตุ', 'meaning_english' => 'pour, note'],
            ['hanzi' => '坏', 'pinyin' => 'huài', 'pinyin_eng' => 'huai', 'meaning_thai' => 'ไม่ดี, พัง', 'meaning_english' => 'bad, broken'],
            ['hanzi' => '久', 'pinyin' => 'jiǔ', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'เวลานาน', 'meaning_english' => 'long time'],
            ['hanzi' => '议', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'อภิปราย, ความเห็น', 'meaning_english' => 'discuss, opinion'],
            ['hanzi' => '礼', 'pinyin' => 'lǐ', 'pinyin_eng' => 'li', 'meaning_thai' => 'พิธี, ของขวัญ', 'meaning_english' => 'ceremony, gift'],
            ['hanzi' => '数', 'pinyin' => 'shù', 'pinyin_eng' => 'shu', 'meaning_thai' => 'จำนวน, นับ', 'meaning_english' => 'number, count'],
            ['hanzi' => '平', 'pinyin' => 'píng', 'pinyin_eng' => 'ping', 'meaning_thai' => 'เรียบ, สงบ', 'meaning_english' => 'flat, peaceful'],
            ['hanzi' => '调', 'pinyin' => 'diào', 'pinyin_eng' => 'diao', 'meaning_thai' => 'ปรับ, จูน', 'meaning_english' => 'tune, adjust'],
            ['hanzi' => '文', 'pinyin' => 'wén', 'pinyin_eng' => 'wen', 'meaning_thai' => 'วัฒนธรรม, ภาษา', 'meaning_english' => 'culture, language'],
            ['hanzi' => '业', 'pinyin' => 'yè', 'pinyin_eng' => 'ye', 'meaning_thai' => 'อุตสาหกรรม, อาชีพ', 'meaning_english' => 'industry, occupation'],
            ['hanzi' => '包', 'pinyin' => 'bāo', 'pinyin_eng' => 'bao', 'meaning_thai' => 'ถุง, ห่อ', 'meaning_english' => 'bag, wrap'],
            ['hanzi' => '参', 'pinyin' => 'cān', 'pinyin_eng' => 'can', 'meaning_thai' => 'เข้าร่วม', 'meaning_english' => 'participate'],
            ['hanzi' => '风', 'pinyin' => 'fēng', 'pinyin_eng' => 'feng', 'meaning_thai' => 'ลม', 'meaning_english' => 'wind'],
            ['hanzi' => '复', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'ทำซ้ำ, สำเนา', 'meaning_english' => 'repeat, duplicate'],
            ['hanzi' => '忘', 'pinyin' => 'wàng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ลืม', 'meaning_english' => 'forget'],
            ['hanzi' => '假', 'pinyin' => 'jiǎ', 'pinyin_eng' => 'jia', 'meaning_thai' => 'ปลอม, วันหยุด', 'meaning_english' => 'fake, holiday'],
            ['hanzi' => '据', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ตามที่', 'meaning_english' => 'according to'],
            ['hanzi' => '嘴', 'pinyin' => 'zuǐ', 'pinyin_eng' => 'zui', 'meaning_thai' => 'ปาก', 'meaning_english' => 'mouth'],
            ['hanzi' => '越', 'pinyin' => 'yuè', 'pinyin_eng' => 'yue', 'meaning_thai' => 'เกิน, มากกว่า', 'meaning_english' => 'exceed, more'],
            ['hanzi' => '简', 'pinyin' => 'jiǎn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ง่าย', 'meaning_english' => 'simple'],
            ['hanzi' => '易', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'ง่าย, เปลี่ยน', 'meaning_english' => 'easy, change'],
            ['hanzi' => '答', 'pinyin' => 'dá', 'pinyin_eng' => 'da', 'meaning_thai' => 'ตอบ, ตอบกลับ', 'meaning_english' => 'answer, reply'],
            ['hanzi' => '乎', 'pinyin' => 'hū', 'pinyin_eng' => 'hu', 'meaning_thai' => '(อนุภาคคำถาม)', 'meaning_english' => '(interrogative particle)'],
            ['hanzi' => '超', 'pinyin' => 'chāo', 'pinyin_eng' => 'chao', 'meaning_thai' => 'เกิน, มากกว่า', 'meaning_english' => 'surpass, exceed'],
            ['hanzi' => '轻', 'pinyin' => 'qīng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'เบา, อ่อนโยน', 'meaning_english' => 'light, gentle'],
            ['hanzi' => '满', 'pinyin' => 'mǎn', 'pinyin_eng' => 'man', 'meaning_thai' => 'เต็ม, พอใจ', 'meaning_english' => 'full, satisfy'],
            ['hanzi' => '静', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'เงียบ, นิ่ง', 'meaning_english' => 'quiet, still'],
            ['hanzi' => '故', 'pinyin' => 'gù', 'pinyin_eng' => 'gu', 'meaning_thai' => 'เหตุผล, สาเหตุ', 'meaning_english' => 'reason, cause'],
            ['hanzi' => '极', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'สุดขั้ว, ขั้ว', 'meaning_english' => 'extreme, pole'],
            ['hanzi' => '讲', 'pinyin' => 'jiǎng', 'pinyin_eng' => 'jiang', 'meaning_thai' => 'พูด, บรรยาย', 'meaning_english' => 'speak, lecture'],
            ['hanzi' => '趣', 'pinyin' => 'qù', 'pinyin_eng' => 'qu', 'meaning_thai' => 'สนใจ, สนุก', 'meaning_english' => 'interest, fun'],
            ['hanzi' => '戏', 'pinyin' => 'xì', 'pinyin_eng' => 'xi', 'meaning_thai' => 'เล่น, ละคร', 'meaning_english' => 'play, drama'],
            ['hanzi' => '容', 'pinyin' => 'róng', 'pinyin_eng' => 'rong', 'meaning_thai' => 'มี, ยอมให้', 'meaning_english' => 'contain, allow'],
            ['hanzi' => '化', 'pinyin' => 'huà', 'pinyin_eng' => 'hua', 'meaning_thai' => 'เปลี่ยนแปลง', 'meaning_english' => 'change, transform'],
            ['hanzi' => '束', 'pinyin' => 'shù', 'pinyin_eng' => 'shu', 'meaning_thai' => 'มัด, ควบคุม', 'meaning_english' => 'bundle, control'],
            ['hanzi' => '终', 'pinyin' => 'zhōng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'จบ, สิ้นสุด', 'meaning_english' => 'end, finish'],
            ['hanzi' => '差', 'pinyin' => 'chā', 'pinyin_eng' => 'cha', 'meaning_thai' => 'ความแตกต่าง, ขาด', 'meaning_english' => 'difference, shortfall'],
            ['hanzi' => '图', 'pinyin' => 'tú', 'pinyin_eng' => 'tu', 'meaning_thai' => 'ภาพ, แผน', 'meaning_english' => 'picture, plan'],
            ['hanzi' => '半', 'pinyin' => 'bàn', 'pinyin_eng' => 'ban', 'meaning_thai' => 'ครึ่ง', 'meaning_english' => 'half'],
            ['hanzi' => '楚', 'pinyin' => 'chǔ', 'pinyin_eng' => 'chu', 'meaning_thai' => 'ชัดเจน, เรียบร้อย', 'meaning_english' => 'clear, neat'],
            ['hanzi' => '市', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ตลาด, เมือง', 'meaning_english' => 'market, city'],
            ['hanzi' => '城', 'pinyin' => 'chéng', 'pinyin_eng' => 'cheng', 'meaning_thai' => 'เมือง, เมืองเล็ก', 'meaning_english' => 'city, town'],
            ['hanzi' => '换', 'pinyin' => 'huàn', 'pinyin_eng' => 'huan', 'meaning_thai' => 'แลกเปลี่ยน, เปลี่ยน', 'meaning_english' => 'exchange, change'],
            ['hanzi' => '船', 'pinyin' => 'chuán', 'pinyin_eng' => 'chuan', 'meaning_thai' => 'เรือ', 'meaning_english' => 'boat, ship'],
            ['hanzi' => '级', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ระดับ', 'meaning_english' => 'level, grade'],
            ['hanzi' => '刻', 'pinyin' => 'kè', 'pinyin_eng' => 'ke', 'meaning_thai' => 'แกะสลัก, 15 นาที', 'meaning_english' => 'carve, quarter hour'],
            ['hanzi' => '迎', 'pinyin' => 'yíng', 'pinyin_eng' => 'ying', 'meaning_thai' => 'ต้อนรับ, พบ', 'meaning_english' => 'welcome, meet'],
            ['hanzi' => '段', 'pinyin' => 'duàn', 'pinyin_eng' => 'duan', 'meaning_thai' => 'ส่วน, ส่วนย่อย', 'meaning_english' => 'section, segment'],
            ['hanzi' => '检', 'pinyin' => 'jiǎn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ตรวจสอบ', 'meaning_english' => 'check, inspect'],
            ['hanzi' => '脸', 'pinyin' => 'liǎn', 'pinyin_eng' => 'lian', 'meaning_thai' => 'ใบหน้า', 'meaning_english' => 'face'],
            ['hanzi' => '择', 'pinyin' => 'zé', 'pinyin_eng' => 'ze', 'meaning_thai' => 'เลือก', 'meaning_english' => 'choose'],
            ['hanzi' => '楼', 'pinyin' => 'lóu', 'pinyin_eng' => 'lou', 'meaning_thai' => 'อาคาร, ชั้น', 'meaning_english' => 'building, floor'],
            ['hanzi' => '皮', 'pinyin' => 'pí', 'pinyin_eng' => 'pi', 'meaning_thai' => 'ผิวหนัง, หนัง', 'meaning_english' => 'skin, leather'],
            ['hanzi' => '练', 'pinyin' => 'liàn', 'pinyin_eng' => 'lian', 'meaning_thai' => 'ฝึกฝน', 'meaning_english' => 'practice'],
            ['hanzi' => '历', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'ประวัติศาสตร์, ประสบการณ์', 'meaning_english' => 'history, experience'],
            ['hanzi' => '山', 'pinyin' => 'shān', 'pinyin_eng' => 'shan', 'meaning_thai' => 'ภูเขา', 'meaning_english' => 'mountain'],
            ['hanzi' => '元', 'pinyin' => 'yuán', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'แรก, หยวน', 'meaning_english' => 'first, yuan'],
            ['hanzi' => '角', 'pinyin' => 'jiǎo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'มุม, เขา', 'meaning_english' => 'angle, horn'],
            ['hanzi' => '街', 'pinyin' => 'jiē', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ถนน', 'meaning_english' => 'street'],
            ['hanzi' => '料', 'pinyin' => 'liào', 'pinyin_eng' => 'liao', 'meaning_thai' => 'วัสดุ, สิ่งของ', 'meaning_english' => 'material, stuff'],
            ['hanzi' => '板', 'pinyin' => 'bǎn', 'pinyin_eng' => 'ban', 'meaning_thai' => 'แผ่นกระดาน', 'meaning_english' => 'board, plank'],
            ['hanzi' => '顾', 'pinyin' => 'gù', 'pinyin_eng' => 'gu', 'meaning_thai' => 'ดูแล, เข้าร่วม', 'meaning_english' => 'look after, attend'],
            ['hanzi' => '遇', 'pinyin' => 'yù', 'pinyin_eng' => 'yu', 'meaning_thai' => 'พบ, เจอ', 'meaning_english' => 'meet, encounter'],
            ['hanzi' => '史', 'pinyin' => 'shǐ', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ประวัติศาสตร์', 'meaning_english' => 'history'],
            ['hanzi' => '画', 'pinyin' => 'huà', 'pinyin_eng' => 'hua', 'meaning_thai' => 'วาดภาพ, ภาพวาด', 'meaning_english' => 'draw, picture'],
            ['hanzi' => '闻', 'pinyin' => 'wén', 'pinyin_eng' => 'wen', 'meaning_thai' => 'ได้ยิน, ดม', 'meaning_english' => 'hear, smell'],
            ['hanzi' => '急', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'เร่งด่วน, วิตกกังวล', 'meaning_english' => 'urgent, anxious'],
            ['hanzi' => '糕', 'pinyin' => 'gāo', 'pinyin_eng' => 'gao', 'meaning_thai' => 'เค้ก', 'meaning_english' => 'cake'],
            ['hanzi' => '脚', 'pinyin' => 'jiǎo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'เท้า', 'meaning_english' => 'foot'],
            ['hanzi' => '聊', 'pinyin' => 'liáo', 'pinyin_eng' => 'liao', 'meaning_thai' => 'สนทนา', 'meaning_english' => 'chat'],
            ['hanzi' => '居', 'pinyin' => 'jū', 'pinyin_eng' => 'ju', 'meaning_thai' => 'อาศัย', 'meaning_english' => 'reside, dwell'],
            ['hanzi' => '词', 'pinyin' => 'cí', 'pinyin_eng' => 'ci', 'meaning_thai' => 'คำ, วลี', 'meaning_english' => 'word, phrase'],
            ['hanzi' => '突', 'pinyin' => 'tū', 'pinyin_eng' => 'tu', 'meaning_thai' => 'กะทันหัน', 'meaning_english' => 'sudden'],
            ['hanzi' => '努', 'pinyin' => 'nǔ', 'pinyin_eng' => 'nu', 'meaning_thai' => 'พยายาม', 'meaning_english' => 'strive, exert'],
            ['hanzi' => '辆', 'pinyin' => 'liàng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'หน่วยนับของยานพาหนะ', 'meaning_english' => 'measure word for vehicles'],
            ['hanzi' => '句', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ประโยค', 'meaning_english' => 'sentence'],
            ['hanzi' => '季', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ฤดูกาล, ไตรมาส', 'meaning_english' => 'season, quarter'],
            ['hanzi' => '双', 'pinyin' => 'shuāng', 'pinyin_eng' => 'shuang', 'meaning_thai' => 'คู่, สอง', 'meaning_english' => 'pair, double'],
            ['hanzi' => '牙', 'pinyin' => 'yá', 'pinyin_eng' => 'ya', 'meaning_thai' => 'ฟัน', 'meaning_english' => 'tooth'],
            ['hanzi' => '南', 'pinyin' => 'nán', 'pinyin_eng' => 'nan', 'meaning_thai' => 'ใต้', 'meaning_english' => 'south'],
            ['hanzi' => '冰', 'pinyin' => 'bīng', 'pinyin_eng' => 'bing', 'meaning_thai' => 'น้ำแข็ง', 'meaning_english' => 'ice'],
            ['hanzi' => '响', 'pinyin' => 'xiǎng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'เสียง, กริ๊ง', 'meaning_english' => 'sound, ring'],
            ['hanzi' => '网', 'pinyin' => 'wǎng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ตาข่าย, เครือข่าย', 'meaning_english' => 'net, network'],
            ['hanzi' => '箱', 'pinyin' => 'xiāng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'กล่อง', 'meaning_english' => 'box, chest'],
            ['hanzi' => '园', 'pinyin' => 'yuán', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'สวน, สวนสาธารณะ', 'meaning_english' => 'garden, park'],
            ['hanzi' => '冒', 'pinyin' => 'mào', 'pinyin_eng' => 'mao', 'meaning_thai' => 'เสี่ยง, ปล่อยออก', 'meaning_english' => 'risk, emit'],
            ['hanzi' => '甜', 'pinyin' => 'tián', 'pinyin_eng' => 'tian', 'meaning_thai' => 'หวาน', 'meaning_english' => 'sweet'],
            ['hanzi' => '香', 'pinyin' => 'xiāng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'หอม, กลิ่นหอม', 'meaning_english' => 'fragrant, aroma'],
            ['hanzi' => '叔', 'pinyin' => 'shū', 'pinyin_eng' => 'shu', 'meaning_thai' => 'ลุง (น้องชายของพ่อ)', 'meaning_english' => 'uncle (father\'s younger brother)'],
            ['hanzi' => '搬', 'pinyin' => 'bān', 'pinyin_eng' => 'ban', 'meaning_thai' => 'ย้าย, ถือ', 'meaning_english' => 'move, carry'],
            ['hanzi' => '迟', 'pinyin' => 'chí', 'pinyin_eng' => 'chi', 'meaning_thai' => 'สาย', 'meaning_english' => 'late'],
            ['hanzi' => '烧', 'pinyin' => 'shāo', 'pinyin_eng' => 'shao', 'meaning_thai' => 'เผา', 'meaning_english' => 'burn'],
            ['hanzi' => '借', 'pinyin' => 'jiè', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ยืม, ให้ยืม', 'meaning_english' => 'borrow, lend'],
            ['hanzi' => '聪', 'pinyin' => 'cōng', 'pinyin_eng' => 'cong', 'meaning_thai' => 'ฉลาด', 'meaning_english' => 'intelligent, clever'],
            ['hanzi' => '腿', 'pinyin' => 'tuǐ', 'pinyin_eng' => 'tui', 'meaning_thai' => 'ขา', 'meaning_english' => 'leg'],
            ['hanzi' => '鞋', 'pinyin' => 'xié', 'pinyin_eng' => 'xie', 'meaning_thai' => 'รองเท้า', 'meaning_english' => 'shoe'],
            ['hanzi' => '树', 'pinyin' => 'shù', 'pinyin_eng' => 'shu', 'meaning_thai' => 'ต้นไม้', 'meaning_english' => 'tree'],
            ['hanzi' => '银', 'pinyin' => 'yín', 'pinyin_eng' => 'yin', 'meaning_thai' => 'เงิน', 'meaning_english' => 'silver'],
            ['hanzi' => '短', 'pinyin' => 'duǎn', 'pinyin_eng' => 'duan', 'meaning_thai' => 'สั้น', 'meaning_english' => 'short'],
            ['hanzi' => '环', 'pinyin' => 'huán', 'pinyin_eng' => 'huan', 'meaning_thai' => 'แหวน, ห่วง', 'meaning_english' => 'ring, loop'],
            ['hanzi' => '哭', 'pinyin' => 'kū', 'pinyin_eng' => 'ku', 'meaning_thai' => 'ร้องไห้', 'meaning_english' => 'cry'],
            ['hanzi' => '康', 'pinyin' => 'kāng', 'pinyin_eng' => 'kang', 'meaning_thai' => 'สุขภาพดี', 'meaning_english' => 'healthy'],
            ['hanzi' => '般', 'pinyin' => 'bān', 'pinyin_eng' => 'ban', 'meaning_thai' => 'ชนิด, ประเภท', 'meaning_english' => 'sort, kind'],
            ['hanzi' => '境', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'ขอบเขต, สถานการณ์', 'meaning_english' => 'border, situation'],
            ['hanzi' => '爷', 'pinyin' => 'yé', 'pinyin_eng' => 'ye', 'meaning_thai' => 'ปู่ (พ่อของพ่อ)', 'meaning_english' => 'grandfather (father\'s side)'],
            ['hanzi' => '灯', 'pinyin' => 'dēng', 'pinyin_eng' => 'deng', 'meaning_thai' => 'โคมไฟ, แสงสว่าง', 'meaning_english' => 'lamp, light'],
            ['hanzi' => '裤', 'pinyin' => 'kù', 'pinyin_eng' => 'ku', 'meaning_thai' => 'กางเกง', 'meaning_english' => 'trousers'],
            ['hanzi' => '盘', 'pinyin' => 'pán', 'pinyin_eng' => 'pan', 'meaning_thai' => 'จาน', 'meaning_english' => 'plate, dish'],
            ['hanzi' => '附', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'ติด, ใกล้', 'meaning_english' => 'attach, near'],
            ['hanzi' => '阳', 'pinyin' => 'yáng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'ดวงอาทิตย์, บวก', 'meaning_english' => 'sun, positive'],
            ['hanzi' => '健', 'pinyin' => 'jiàn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'สุขภาพดี', 'meaning_english' => 'healthy'],
            ['hanzi' => '较', 'pinyin' => 'jiào', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'เปรียบเทียบ, ค่อนข้าง', 'meaning_english' => 'compare, relatively'],
            ['hanzi' => '耳', 'pinyin' => 'ěr', 'pinyin_eng' => 'er', 'meaning_thai' => 'หู', 'meaning_english' => 'ear'],
            ['hanzi' => '草', 'pinyin' => 'cǎo', 'pinyin_eng' => 'cao', 'meaning_thai' => 'หญ้า', 'meaning_english' => 'grass'],
            ['hanzi' => '层', 'pinyin' => 'céng', 'pinyin_eng' => 'ceng', 'meaning_thai' => 'ชั้น', 'meaning_english' => 'layer, floor'],
            ['hanzi' => '末', 'pinyin' => 'mò', 'pinyin_eng' => 'mo', 'meaning_thai' => 'สิ้นสุด, ปลาย', 'meaning_english' => 'end, tip'],
            ['hanzi' => '铁', 'pinyin' => 'tiě', 'pinyin_eng' => 'tie', 'meaning_thai' => 'เหล็ก', 'meaning_english' => 'iron'],
            ['hanzi' => '黄', 'pinyin' => 'huáng', 'pinyin_eng' => 'huang', 'meaning_thai' => 'สีเหลือง', 'meaning_english' => 'yellow'],
            ['hanzi' => '夏', 'pinyin' => 'xià', 'pinyin_eng' => 'xia', 'meaning_thai' => 'ฤดูร้อน', 'meaning_english' => 'summer'],
            ['hanzi' => '舒', 'pinyin' => 'shū', 'pinyin_eng' => 'shu', 'meaning_thai' => 'สบาย', 'meaning_english' => 'comfortable'],
            ['hanzi' => '旧', 'pinyin' => 'jiù', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'เก่า, ใช้แล้ว', 'meaning_english' => 'old, used'],
            ['hanzi' => '蓝', 'pinyin' => 'lán', 'pinyin_eng' => 'lan', 'meaning_thai' => 'สีฟ้า', 'meaning_english' => 'blue'],
            ['hanzi' => '疼', 'pinyin' => 'téng', 'pinyin_eng' => 'teng', 'meaning_thai' => 'เจ็บ, ปวด', 'meaning_english' => 'pain, ache'],
            ['hanzi' => '河', 'pinyin' => 'hé', 'pinyin_eng' => 'he', 'meaning_thai' => 'แม่น้ำ', 'meaning_english' => 'river'],
            ['hanzi' => '鸟', 'pinyin' => 'niǎo', 'pinyin_eng' => 'niao', 'meaning_thai' => 'นก', 'meaning_english' => 'bird'],
            ['hanzi' => '骑', 'pinyin' => 'qí', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ขี่ (ม้า, จักรยาน)', 'meaning_english' => 'ride (a horse, bike)'],
            ['hanzi' => '饿', 'pinyin' => 'è', 'pinyin_eng' => 'e', 'meaning_thai' => 'หิว', 'meaning_english' => 'hungry'],
            ['hanzi' => '瓶', 'pinyin' => 'píng', 'pinyin_eng' => 'ping', 'meaning_thai' => 'ขวด', 'meaning_english' => 'bottle'],
            ['hanzi' => '典', 'pinyin' => 'diǎn', 'pinyin_eng' => 'dian', 'meaning_thai' => 'มาตรฐาน, พจนานุกรม', 'meaning_english' => 'standard, dictionary'],
            ['hanzi' => '育', 'pinyin' => 'yù', 'pinyin_eng' => 'yu', 'meaning_thai' => 'การศึกษา, เลี้ยงดู', 'meaning_english' => 'educate, nurture'],
            ['hanzi' => '净', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'สะอาด, บริสุทธิ์', 'meaning_english' => 'clean, pure'],
            ['hanzi' => '李', 'pinyin' => 'lǐ', 'pinyin_eng' => 'li', 'meaning_thai' => 'บ๊วย, นามสกุล', 'meaning_english' => 'plum, surname'],
            ['hanzi' => '鲜', 'pinyin' => 'xiān', 'pinyin_eng' => 'xian', 'meaning_thai' => 'สด, อร่อย', 'meaning_english' => 'fresh, delicious'],
            ['hanzi' => '扫', 'pinyin' => 'sǎo', 'pinyin_eng' => 'sao', 'meaning_thai' => 'กวาด', 'meaning_english' => 'sweep'],
            ['hanzi' => '惯', 'pinyin' => 'guàn', 'pinyin_eng' => 'guan', 'meaning_thai' => 'คุ้นเคยกับ', 'meaning_english' => 'accustomed to'],
            ['hanzi' => '邮', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'จดหมาย', 'meaning_english' => 'mail'],
            ['hanzi' => '帽', 'pinyin' => 'mào', 'pinyin_eng' => 'mao', 'meaning_thai' => 'หมวก', 'meaning_english' => 'hat'],
            ['hanzi' => '啤', 'pinyin' => 'pí', 'pinyin_eng' => 'pi', 'meaning_thai' => 'เบียร์', 'meaning_english' => 'beer'],
            ['hanzi' => '梯', 'pinyin' => 'tī', 'pinyin_eng' => 'ti', 'meaning_thai' => 'บันได', 'meaning_english' => 'ladder'],
            ['hanzi' => '鼻', 'pinyin' => 'bí', 'pinyin_eng' => 'bi', 'meaning_thai' => 'จมูก', 'meaning_english' => 'nose'],
            ['hanzi' => '绿', 'pinyin' => 'lǜ', 'pinyin_eng' => 'lv', 'meaning_thai' => 'สีเขียว', 'meaning_english' => 'green'],
            ['hanzi' => '熊', 'pinyin' => 'xióng', 'pinyin_eng' => 'xiong', 'meaning_thai' => 'หมี', 'meaning_english' => 'bear'],
            ['hanzi' => '胖', 'pinyin' => 'pàng', 'pinyin_eng' => 'pang', 'meaning_thai' => 'อ้วน', 'meaning_english' => 'fat'],
            ['hanzi' => '爬', 'pinyin' => 'pá', 'pinyin_eng' => 'pa', 'meaning_thai' => 'ปีน', 'meaning_english' => 'climb'],
            ['hanzi' => '邻', 'pinyin' => 'lín', 'pinyin_eng' => 'lin', 'meaning_thai' => 'เพื่อนบ้าน', 'meaning_english' => 'neighbor'],
            ['hanzi' => '春', 'pinyin' => 'chūn', 'pinyin_eng' => 'chun', 'meaning_thai' => 'ฤดูใบไม้ผลิ', 'meaning_english' => 'spring (season)'],
            ['hanzi' => '朵', 'pinyin' => 'duǒ', 'pinyin_eng' => 'duo', 'meaning_thai' => 'ดอกไม้, หน่วยนับดอกไม้', 'meaning_english' => 'flower, measure word for flowers'],
            ['hanzi' => '饮', 'pinyin' => 'yǐn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'ดื่ม', 'meaning_english' => 'drink'],
            ['hanzi' => '裙', 'pinyin' => 'qún', 'pinyin_eng' => 'qun', 'meaning_thai' => 'กระโปรง', 'meaning_english' => 'skirt'],
            ['hanzi' => '澡', 'pinyin' => 'zǎo', 'pinyin_eng' => 'zao', 'meaning_thai' => 'อาบน้ำ', 'meaning_english' => 'bath'],
            ['hanzi' => '渴', 'pinyin' => 'kě', 'pinyin_eng' => 'ke', 'meaning_thai' => 'กระหาย', 'meaning_english' => 'thirsty'],
            ['hanzi' => '衫', 'pinyin' => 'shān', 'pinyin_eng' => 'shan', 'meaning_thai' => 'เสื้อเชิ้ต', 'meaning_english' => 'shirt'],
            ['hanzi' => '刷', 'pinyin' => 'shuā', 'pinyin_eng' => 'shua', 'meaning_thai' => 'แปรง', 'meaning_english' => 'brush'],
            ['hanzi' => '衬', 'pinyin' => 'chèn', 'pinyin_eng' => 'chen', 'meaning_thai' => 'ซับใน, ด้านใน', 'meaning_english' => 'lining, inner'],
            ['hanzi' => '姨', 'pinyin' => 'yí', 'pinyin_eng' => 'yi', 'meaning_thai' => 'น้า (น้องสาวของแม่)', 'meaning_english' => 'aunt (mother\'s sister)'],
            ['hanzi' => '秋', 'pinyin' => 'qiū', 'pinyin_eng' => 'qiu', 'meaning_thai' => 'ฤดูใบไม้ร่วง', 'meaning_english' => 'autumn'],
            ['hanzi' => '碗', 'pinyin' => 'wǎn', 'pinyin_eng' => 'wan', 'meaning_thai' => 'ชาม', 'meaning_english' => 'bowl'],
            ['hanzi' => '绩', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ความดี, ความสำเร็จ', 'meaning_english' => 'merit, accomplishment'],
            ['hanzi' => '冬', 'pinyin' => 'dōng', 'pinyin_eng' => 'dong', 'meaning_thai' => 'ฤดูหนาว', 'meaning_english' => 'winter'],
            ['hanzi' => '刮', 'pinyin' => 'guā', 'pinyin_eng' => 'gua', 'meaning_thai' => 'ขูด, โกน', 'meaning_english' => 'scrape, shave'],
            ['hanzi' => '瘦', 'pinyin' => 'shòu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'ผอม', 'meaning_english' => 'thin, lean'],
            ['hanzi' => '矮', 'pinyin' => 'ǎi', 'pinyin_eng' => 'ai', 'meaning_thai' => 'เตี้ย', 'meaning_english' => 'short (height)'],
            ['hanzi' => '炼', 'pinyin' => 'liàn', 'pinyin_eng' => 'lian', 'meaning_thai' => 'หลอม, กลั่น', 'meaning_english' => 'smelt, refine'],
            ['hanzi' => '伞', 'pinyin' => 'sǎn', 'pinyin_eng' => 'san', 'meaning_thai' => 'ร่ม', 'meaning_english' => 'umbrella'],
            ['hanzi' => '饱', 'pinyin' => 'bǎo', 'pinyin_eng' => 'bao', 'meaning_thai' => 'อิ่ม', 'meaning_english' => 'full (from eating)'],
            ['hanzi' => '锻', 'pinyin' => 'duàn', 'pinyin_eng' => 'duan', 'meaning_thai' => 'หลอม, ปรับสภาพ', 'meaning_english' => 'forge, temper'],
            ['hanzi' => '蕉', 'pinyin' => 'jiāo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'กล้วย', 'meaning_english' => 'banana'],
            ['hanzi' => '斤', 'pinyin' => 'jīn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'ชั่ง (หน่วยน้ำหนัก), ครึ่งกิโลกรัม', 'meaning_english' => 'catty (weight unit), half a kilogram'],
            ['hanzi' => '筷', 'pinyin' => 'kuài', 'pinyin_eng' => 'kuai', 'meaning_thai' => 'ตะเกียบ', 'meaning_english' => 'chopsticks'],
        ]);

        // hanzi_categories HSK 3 (270)
        DB::table('hanzi_categories')->insert([
            ['hanzi_id' => 348, 'category_id' => 3],
            ['hanzi_id' => 349, 'category_id' => 3],
            ['hanzi_id' => 350, 'category_id' => 3],
            ['hanzi_id' => 351, 'category_id' => 3],
            ['hanzi_id' => 352, 'category_id' => 3],
            ['hanzi_id' => 353, 'category_id' => 3],
            ['hanzi_id' => 354, 'category_id' => 3],
            ['hanzi_id' => 355, 'category_id' => 3],
            ['hanzi_id' => 356, 'category_id' => 3],
            ['hanzi_id' => 357, 'category_id' => 3],
            ['hanzi_id' => 358, 'category_id' => 3],
            ['hanzi_id' => 359, 'category_id' => 3],
            ['hanzi_id' => 360, 'category_id' => 3],
            ['hanzi_id' => 361, 'category_id' => 3],
            ['hanzi_id' => 362, 'category_id' => 3],
            ['hanzi_id' => 363, 'category_id' => 3],
            ['hanzi_id' => 364, 'category_id' => 3],
            ['hanzi_id' => 365, 'category_id' => 3],
            ['hanzi_id' => 366, 'category_id' => 3],
            ['hanzi_id' => 367, 'category_id' => 3],
            ['hanzi_id' => 368, 'category_id' => 3],
            ['hanzi_id' => 369, 'category_id' => 3],
            ['hanzi_id' => 370, 'category_id' => 3],
            ['hanzi_id' => 371, 'category_id' => 3],
            ['hanzi_id' => 372, 'category_id' => 3],
            ['hanzi_id' => 373, 'category_id' => 3],
            ['hanzi_id' => 374, 'category_id' => 3],
            ['hanzi_id' => 375, 'category_id' => 3],
            ['hanzi_id' => 376, 'category_id' => 3],
            ['hanzi_id' => 377, 'category_id' => 3],
            ['hanzi_id' => 378, 'category_id' => 3],
            ['hanzi_id' => 379, 'category_id' => 3],
            ['hanzi_id' => 380, 'category_id' => 3],
            ['hanzi_id' => 381, 'category_id' => 3],
            ['hanzi_id' => 382, 'category_id' => 3],
            ['hanzi_id' => 383, 'category_id' => 3],
            ['hanzi_id' => 384, 'category_id' => 3],
            ['hanzi_id' => 385, 'category_id' => 3],
            ['hanzi_id' => 386, 'category_id' => 3],
            ['hanzi_id' => 387, 'category_id' => 3],
            ['hanzi_id' => 388, 'category_id' => 3],
            ['hanzi_id' => 389, 'category_id' => 3],
            ['hanzi_id' => 390, 'category_id' => 3],
            ['hanzi_id' => 391, 'category_id' => 3],
            ['hanzi_id' => 392, 'category_id' => 3],
            ['hanzi_id' => 393, 'category_id' => 3],
            ['hanzi_id' => 394, 'category_id' => 3],
            ['hanzi_id' => 395, 'category_id' => 3],
            ['hanzi_id' => 396, 'category_id' => 3],
            ['hanzi_id' => 397, 'category_id' => 3],
            ['hanzi_id' => 398, 'category_id' => 3],
            ['hanzi_id' => 399, 'category_id' => 3],
            ['hanzi_id' => 400, 'category_id' => 3],
            ['hanzi_id' => 401, 'category_id' => 3],
            ['hanzi_id' => 402, 'category_id' => 3],
            ['hanzi_id' => 403, 'category_id' => 3],
            ['hanzi_id' => 404, 'category_id' => 3],
            ['hanzi_id' => 405, 'category_id' => 3],
            ['hanzi_id' => 406, 'category_id' => 3],
            ['hanzi_id' => 407, 'category_id' => 3],
            ['hanzi_id' => 408, 'category_id' => 3],
            ['hanzi_id' => 409, 'category_id' => 3],
            ['hanzi_id' => 410, 'category_id' => 3],
            ['hanzi_id' => 411, 'category_id' => 3],
            ['hanzi_id' => 412, 'category_id' => 3],
            ['hanzi_id' => 413, 'category_id' => 3],
            ['hanzi_id' => 414, 'category_id' => 3],
            ['hanzi_id' => 415, 'category_id' => 3],
            ['hanzi_id' => 416, 'category_id' => 3],
            ['hanzi_id' => 417, 'category_id' => 3],
            ['hanzi_id' => 418, 'category_id' => 3],
            ['hanzi_id' => 419, 'category_id' => 3],
            ['hanzi_id' => 420, 'category_id' => 3],
            ['hanzi_id' => 421, 'category_id' => 3],
            ['hanzi_id' => 422, 'category_id' => 3],
            ['hanzi_id' => 423, 'category_id' => 3],
            ['hanzi_id' => 424, 'category_id' => 3],
            ['hanzi_id' => 425, 'category_id' => 3],
            ['hanzi_id' => 426, 'category_id' => 3],
            ['hanzi_id' => 427, 'category_id' => 3],
            ['hanzi_id' => 428, 'category_id' => 3],
            ['hanzi_id' => 429, 'category_id' => 3],
            ['hanzi_id' => 430, 'category_id' => 3],
            ['hanzi_id' => 431, 'category_id' => 3],
            ['hanzi_id' => 432, 'category_id' => 3],
            ['hanzi_id' => 433, 'category_id' => 3],
            ['hanzi_id' => 434, 'category_id' => 3],
            ['hanzi_id' => 435, 'category_id' => 3],
            ['hanzi_id' => 436, 'category_id' => 3],
            ['hanzi_id' => 437, 'category_id' => 3],
            ['hanzi_id' => 438, 'category_id' => 3],
            ['hanzi_id' => 439, 'category_id' => 3],
            ['hanzi_id' => 440, 'category_id' => 3],
            ['hanzi_id' => 441, 'category_id' => 3],
            ['hanzi_id' => 442, 'category_id' => 3],
            ['hanzi_id' => 443, 'category_id' => 3],
            ['hanzi_id' => 444, 'category_id' => 3],
            ['hanzi_id' => 445, 'category_id' => 3],
            ['hanzi_id' => 446, 'category_id' => 3],
            ['hanzi_id' => 447, 'category_id' => 3],
            ['hanzi_id' => 448, 'category_id' => 3],
            ['hanzi_id' => 449, 'category_id' => 3],
            ['hanzi_id' => 450, 'category_id' => 3],
            ['hanzi_id' => 451, 'category_id' => 3],
            ['hanzi_id' => 452, 'category_id' => 3],
            ['hanzi_id' => 453, 'category_id' => 3],
            ['hanzi_id' => 454, 'category_id' => 3],
            ['hanzi_id' => 455, 'category_id' => 3],
            ['hanzi_id' => 456, 'category_id' => 3],
            ['hanzi_id' => 457, 'category_id' => 3],
            ['hanzi_id' => 458, 'category_id' => 3],
            ['hanzi_id' => 459, 'category_id' => 3],
            ['hanzi_id' => 460, 'category_id' => 3],
            ['hanzi_id' => 461, 'category_id' => 3],
            ['hanzi_id' => 462, 'category_id' => 3],
            ['hanzi_id' => 463, 'category_id' => 3],
            ['hanzi_id' => 464, 'category_id' => 3],
            ['hanzi_id' => 465, 'category_id' => 3],
            ['hanzi_id' => 466, 'category_id' => 3],
            ['hanzi_id' => 467, 'category_id' => 3],
            ['hanzi_id' => 468, 'category_id' => 3],
            ['hanzi_id' => 469, 'category_id' => 3],
            ['hanzi_id' => 470, 'category_id' => 3],
            ['hanzi_id' => 471, 'category_id' => 3],
            ['hanzi_id' => 472, 'category_id' => 3],
            ['hanzi_id' => 473, 'category_id' => 3],
            ['hanzi_id' => 474, 'category_id' => 3],
            ['hanzi_id' => 475, 'category_id' => 3],
            ['hanzi_id' => 476, 'category_id' => 3],
            ['hanzi_id' => 477, 'category_id' => 3],
            ['hanzi_id' => 478, 'category_id' => 3],
            ['hanzi_id' => 479, 'category_id' => 3],
            ['hanzi_id' => 480, 'category_id' => 3],
            ['hanzi_id' => 481, 'category_id' => 3],
            ['hanzi_id' => 482, 'category_id' => 3],
            ['hanzi_id' => 483, 'category_id' => 3],
            ['hanzi_id' => 484, 'category_id' => 3],
            ['hanzi_id' => 485, 'category_id' => 3],
            ['hanzi_id' => 486, 'category_id' => 3],
            ['hanzi_id' => 487, 'category_id' => 3],
            ['hanzi_id' => 488, 'category_id' => 3],
            ['hanzi_id' => 489, 'category_id' => 3],
            ['hanzi_id' => 490, 'category_id' => 3],
            ['hanzi_id' => 491, 'category_id' => 3],
            ['hanzi_id' => 492, 'category_id' => 3],
            ['hanzi_id' => 493, 'category_id' => 3],
            ['hanzi_id' => 494, 'category_id' => 3],
            ['hanzi_id' => 495, 'category_id' => 3],
            ['hanzi_id' => 496, 'category_id' => 3],
            ['hanzi_id' => 497, 'category_id' => 3],
            ['hanzi_id' => 498, 'category_id' => 3],
            ['hanzi_id' => 499, 'category_id' => 3],
            ['hanzi_id' => 500, 'category_id' => 3],
            ['hanzi_id' => 501, 'category_id' => 3],
            ['hanzi_id' => 502, 'category_id' => 3],
            ['hanzi_id' => 503, 'category_id' => 3],
            ['hanzi_id' => 504, 'category_id' => 3],
            ['hanzi_id' => 505, 'category_id' => 3],
            ['hanzi_id' => 506, 'category_id' => 3],
            ['hanzi_id' => 507, 'category_id' => 3],
            ['hanzi_id' => 508, 'category_id' => 3],
            ['hanzi_id' => 509, 'category_id' => 3],
            ['hanzi_id' => 510, 'category_id' => 3],
            ['hanzi_id' => 511, 'category_id' => 3],
            ['hanzi_id' => 512, 'category_id' => 3],
            ['hanzi_id' => 513, 'category_id' => 3],
            ['hanzi_id' => 514, 'category_id' => 3],
            ['hanzi_id' => 515, 'category_id' => 3],
            ['hanzi_id' => 516, 'category_id' => 3],
            ['hanzi_id' => 517, 'category_id' => 3],
            ['hanzi_id' => 518, 'category_id' => 3],
            ['hanzi_id' => 519, 'category_id' => 3],
            ['hanzi_id' => 520, 'category_id' => 3],
            ['hanzi_id' => 521, 'category_id' => 3],
            ['hanzi_id' => 522, 'category_id' => 3],
            ['hanzi_id' => 523, 'category_id' => 3],
            ['hanzi_id' => 524, 'category_id' => 3],
            ['hanzi_id' => 525, 'category_id' => 3],
            ['hanzi_id' => 526, 'category_id' => 3],
            ['hanzi_id' => 527, 'category_id' => 3],
            ['hanzi_id' => 528, 'category_id' => 3],
            ['hanzi_id' => 529, 'category_id' => 3],
            ['hanzi_id' => 530, 'category_id' => 3],
            ['hanzi_id' => 531, 'category_id' => 3],
            ['hanzi_id' => 532, 'category_id' => 3],
            ['hanzi_id' => 533, 'category_id' => 3],
            ['hanzi_id' => 534, 'category_id' => 3],
            ['hanzi_id' => 535, 'category_id' => 3],
            ['hanzi_id' => 536, 'category_id' => 3],
            ['hanzi_id' => 537, 'category_id' => 3],
            ['hanzi_id' => 538, 'category_id' => 3],
            ['hanzi_id' => 539, 'category_id' => 3],
            ['hanzi_id' => 540, 'category_id' => 3],
            ['hanzi_id' => 541, 'category_id' => 3],
            ['hanzi_id' => 542, 'category_id' => 3],
            ['hanzi_id' => 543, 'category_id' => 3],
            ['hanzi_id' => 544, 'category_id' => 3],
            ['hanzi_id' => 545, 'category_id' => 3],
            ['hanzi_id' => 546, 'category_id' => 3],
            ['hanzi_id' => 547, 'category_id' => 3],
            ['hanzi_id' => 548, 'category_id' => 3],
            ['hanzi_id' => 549, 'category_id' => 3],
            ['hanzi_id' => 550, 'category_id' => 3],
            ['hanzi_id' => 551, 'category_id' => 3],
            ['hanzi_id' => 552, 'category_id' => 3],
            ['hanzi_id' => 553, 'category_id' => 3],
            ['hanzi_id' => 554, 'category_id' => 3],
            ['hanzi_id' => 555, 'category_id' => 3],
            ['hanzi_id' => 556, 'category_id' => 3],
            ['hanzi_id' => 557, 'category_id' => 3],
            ['hanzi_id' => 558, 'category_id' => 3],
            ['hanzi_id' => 559, 'category_id' => 3],
            ['hanzi_id' => 560, 'category_id' => 3],
            ['hanzi_id' => 561, 'category_id' => 3],
            ['hanzi_id' => 562, 'category_id' => 3],
            ['hanzi_id' => 563, 'category_id' => 3],
            ['hanzi_id' => 564, 'category_id' => 3],
            ['hanzi_id' => 565, 'category_id' => 3],
            ['hanzi_id' => 566, 'category_id' => 3],
            ['hanzi_id' => 567, 'category_id' => 3],
            ['hanzi_id' => 568, 'category_id' => 3],
            ['hanzi_id' => 569, 'category_id' => 3],
            ['hanzi_id' => 570, 'category_id' => 3],
            ['hanzi_id' => 571, 'category_id' => 3],
            ['hanzi_id' => 572, 'category_id' => 3],
            ['hanzi_id' => 573, 'category_id' => 3],
            ['hanzi_id' => 574, 'category_id' => 3],
            ['hanzi_id' => 575, 'category_id' => 3],
            ['hanzi_id' => 576, 'category_id' => 3],
            ['hanzi_id' => 577, 'category_id' => 3],
            ['hanzi_id' => 578, 'category_id' => 3],
            ['hanzi_id' => 579, 'category_id' => 3],
            ['hanzi_id' => 580, 'category_id' => 3],
            ['hanzi_id' => 581, 'category_id' => 3],
            ['hanzi_id' => 582, 'category_id' => 3],
            ['hanzi_id' => 583, 'category_id' => 3],
            ['hanzi_id' => 584, 'category_id' => 3],
            ['hanzi_id' => 585, 'category_id' => 3],
            ['hanzi_id' => 586, 'category_id' => 3],
            ['hanzi_id' => 587, 'category_id' => 3],
            ['hanzi_id' => 588, 'category_id' => 3],
            ['hanzi_id' => 589, 'category_id' => 3],
            ['hanzi_id' => 590, 'category_id' => 3],
            ['hanzi_id' => 591, 'category_id' => 3],
            ['hanzi_id' => 592, 'category_id' => 3],
            ['hanzi_id' => 593, 'category_id' => 3],
            ['hanzi_id' => 594, 'category_id' => 3],
            ['hanzi_id' => 595, 'category_id' => 3],
            ['hanzi_id' => 596, 'category_id' => 3],
            ['hanzi_id' => 597, 'category_id' => 3],
            ['hanzi_id' => 598, 'category_id' => 3],
            ['hanzi_id' => 599, 'category_id' => 3],
            ['hanzi_id' => 600, 'category_id' => 3],
            ['hanzi_id' => 601, 'category_id' => 3],
            ['hanzi_id' => 602, 'category_id' => 3],
            ['hanzi_id' => 603, 'category_id' => 3],
            ['hanzi_id' => 604, 'category_id' => 3],
            ['hanzi_id' => 605, 'category_id' => 3],
            ['hanzi_id' => 606, 'category_id' => 3],
            ['hanzi_id' => 607, 'category_id' => 3],
            ['hanzi_id' => 608, 'category_id' => 3],
            ['hanzi_id' => 609, 'category_id' => 3],
            ['hanzi_id' => 610, 'category_id' => 3],
            ['hanzi_id' => 611, 'category_id' => 3],
            ['hanzi_id' => 612, 'category_id' => 3],
            ['hanzi_id' => 613, 'category_id' => 3],
            ['hanzi_id' => 614, 'category_id' => 3],
            ['hanzi_id' => 615, 'category_id' => 3],
            ['hanzi_id' => 616, 'category_id' => 3],
            ['hanzi_id' => 617, 'category_id' => 3],
        ]);
    }
}
